//
// SMITH3 - generates spin-free multireference electron correlation programs.
// Filename: main.cc
// Copyright (C) 2012 Toru Shiozaki
//
// Author: Toru Shiozaki <shiozaki@northwestern.edu>
// Maintainer: Shiozaki group
//
// This file is part of the SMITH3 package.
//
// The SMITH3 package is free software; you can redistribute it and/or modify
// it under the terms of the GNU Library General Public License as published by
// the Free Software Foundation; either version 2, or (at your option)
// any later version.
//
// The SMITH3 package is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public License
// along with the SMITH3 package; see COPYING.  If not, write to
// the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
//


// This program is supposed to perform Wick's theorem for multireference problems.
// Spin averaged quantities assumed.

#include <iostream>
#include <fstream>
#include <list>
#include <string>
#include "equation.h"
#include "tree.h"

using namespace std;
using namespace smith;

int main() {

  string theory="CAS_all_active"; 
  shared_ptr<Op> proj0(new Op("proj", "c", "c", "x", "x"));
  shared_ptr<Op> proj1(new Op("proj", "x", "c", "x", "x"));
  shared_ptr<Op> proj2(new Op("proj", "c", "c", "a", "x"));
  shared_ptr<Op> proj3(new Op("proj", "x", "c", "a", "x"));
  shared_ptr<Op> proj4(new Op("proj", "x", "x", "a", "x"));
  shared_ptr<Op> proj5(new Op("proj", "c", "c", "a", "a"));
  shared_ptr<Op> proj6(new Op("proj", "x", "c", "a", "a"));
  shared_ptr<Op> proj7(new Op("proj", "x", "x", "a", "a"));
  shared_ptr<Op> t20(new Op("t2", "x", "x", "c", "c"));
  shared_ptr<Op> t21(new Op("t2", "x", "x", "x", "c"));
  shared_ptr<Op> t22(new Op("t2", "a", "x", "c", "c"));
  shared_ptr<Op> t23(new Op("t2", "a", "x", "x", "c"));
  shared_ptr<Op> t24(new Op("t2", "a", "x", "x", "x"));
  shared_ptr<Op> t25(new Op("t2", "a", "a", "c", "c"));
  shared_ptr<Op> t26(new Op("t2", "a", "a", "x", "c"));
  shared_ptr<Op> t27(new Op("t2", "a", "a", "x", "x"));
  shared_ptr<Op> r0(new Op("r", "x", "x", "c", "c"));
  shared_ptr<Op> r1(new Op("r", "x", "x", "x", "c"));
  shared_ptr<Op> r2(new Op("r", "a", "x", "c", "c"));
  shared_ptr<Op> r3(new Op("r", "a", "x", "x", "c"));
  shared_ptr<Op> r4(new Op("r", "a", "x", "x", "x"));
  shared_ptr<Op> r5(new Op("r", "a", "a", "c", "c"));
  shared_ptr<Op> r6(new Op("r", "a", "a", "x", "c"));
  shared_ptr<Op> r7(new Op("r", "a", "a", "x", "x"));
  shared_ptr<Op> f1(new Op("f1", "g", "g"));
  shared_ptr<Op> v2(new Op("v2", "g", "g", "g", "g"));
  shared_ptr<Op> proje(new Op("proj"));
  shared_ptr<Op> t2dagger0(new Op("t2dagger", "c", "c", "x", "x"));
  shared_ptr<Op> t2dagger1(new Op("t2dagger", "x", "c", "x", "x"));
  shared_ptr<Op> t2dagger2(new Op("t2dagger", "c", "c", "a", "x"));
  shared_ptr<Op> t2dagger3(new Op("t2dagger", "x", "c", "a", "x"));
  shared_ptr<Op> t2dagger4(new Op("t2dagger", "x", "x", "a", "x"));
  shared_ptr<Op> t2dagger5(new Op("t2dagger", "c", "c", "a", "a"));
  shared_ptr<Op> t2dagger6(new Op("t2dagger", "x", "c", "a", "a"));
  shared_ptr<Op> t2dagger7(new Op("t2dagger", "x", "x", "a", "a"));
  list<shared_ptr<Op> > da0 = {proj0, f1, t20};
  list<shared_ptr<Op> > da1 = {proj0, f1, t21};
  list<shared_ptr<Op> > da2 = {proj0, f1, t22};
  list<shared_ptr<Op> > da3 = {proj0, f1, t23};
  list<shared_ptr<Op> > da4 = {proj0, f1, t24};
  list<shared_ptr<Op> > da5 = {proj0, f1, t25};
  list<shared_ptr<Op> > da6 = {proj0, f1, t26};
  list<shared_ptr<Op> > da7 = {proj0, f1, t27};
  list<shared_ptr<Op> > da8 = {proj1, f1, t20};
  list<shared_ptr<Op> > da9 = {proj1, f1, t21};
  list<shared_ptr<Op> > da10 = {proj1, f1, t22};
  list<shared_ptr<Op> > da11 = {proj1, f1, t23};
  list<shared_ptr<Op> > da12 = {proj1, f1, t24};
  list<shared_ptr<Op> > da13 = {proj1, f1, t25};
  list<shared_ptr<Op> > da14 = {proj1, f1, t26};
  list<shared_ptr<Op> > da15 = {proj1, f1, t27};
  list<shared_ptr<Op> > da16 = {proj2, f1, t20};
  list<shared_ptr<Op> > da17 = {proj2, f1, t21};
  list<shared_ptr<Op> > da18 = {proj2, f1, t22};
  list<shared_ptr<Op> > da19 = {proj2, f1, t23};
  list<shared_ptr<Op> > da20 = {proj2, f1, t24};
  list<shared_ptr<Op> > da21 = {proj2, f1, t25};
  list<shared_ptr<Op> > da22 = {proj2, f1, t26};
  list<shared_ptr<Op> > da23 = {proj2, f1, t27};
  list<shared_ptr<Op> > da24 = {proj3, f1, t20};
  list<shared_ptr<Op> > da25 = {proj3, f1, t21};
  list<shared_ptr<Op> > da26 = {proj3, f1, t22};
  list<shared_ptr<Op> > da27 = {proj3, f1, t23};
  list<shared_ptr<Op> > da28 = {proj3, f1, t24};
  list<shared_ptr<Op> > da29 = {proj3, f1, t25};
  list<shared_ptr<Op> > da30 = {proj3, f1, t26};
  list<shared_ptr<Op> > da31 = {proj3, f1, t27};
  list<shared_ptr<Op> > da32 = {proj4, f1, t20};
  list<shared_ptr<Op> > da33 = {proj4, f1, t21};
  list<shared_ptr<Op> > da34 = {proj4, f1, t22};
  list<shared_ptr<Op> > da35 = {proj4, f1, t23};
  list<shared_ptr<Op> > da36 = {proj4, f1, t24};
  list<shared_ptr<Op> > da37 = {proj4, f1, t25};
  list<shared_ptr<Op> > da38 = {proj4, f1, t26};
  list<shared_ptr<Op> > da39 = {proj4, f1, t27};
  list<shared_ptr<Op> > da40 = {proj5, f1, t20};
  list<shared_ptr<Op> > da41 = {proj5, f1, t21};
  list<shared_ptr<Op> > da42 = {proj5, f1, t22};
  list<shared_ptr<Op> > da43 = {proj5, f1, t23};
  list<shared_ptr<Op> > da44 = {proj5, f1, t24};
  list<shared_ptr<Op> > da45 = {proj5, f1, t25};
  list<shared_ptr<Op> > da46 = {proj5, f1, t26};
  list<shared_ptr<Op> > da47 = {proj5, f1, t27};
  list<shared_ptr<Op> > da48 = {proj6, f1, t20};
  list<shared_ptr<Op> > da49 = {proj6, f1, t21};
  list<shared_ptr<Op> > da50 = {proj6, f1, t22};
  list<shared_ptr<Op> > da51 = {proj6, f1, t23};
  list<shared_ptr<Op> > da52 = {proj6, f1, t24};
  list<shared_ptr<Op> > da53 = {proj6, f1, t25};
  list<shared_ptr<Op> > da54 = {proj6, f1, t26};
  list<shared_ptr<Op> > da55 = {proj6, f1, t27};
  list<shared_ptr<Op> > da56 = {proj7, f1, t20};
  list<shared_ptr<Op> > da57 = {proj7, f1, t21};
  list<shared_ptr<Op> > da58 = {proj7, f1, t22};
  list<shared_ptr<Op> > da59 = {proj7, f1, t23};
  list<shared_ptr<Op> > da60 = {proj7, f1, t24};
  list<shared_ptr<Op> > da61 = {proj7, f1, t25};
  list<shared_ptr<Op> > da62 = {proj7, f1, t26};
  list<shared_ptr<Op> > da63 = {proj7, f1, t27};
  list<shared_ptr<Op> > db0 = {proj0, t20};
  list<shared_ptr<Op> > db1 = {proj0, t21};
  list<shared_ptr<Op> > db2 = {proj0, t22};
  list<shared_ptr<Op> > db3 = {proj0, t23};
  list<shared_ptr<Op> > db4 = {proj0, t24};
  list<shared_ptr<Op> > db5 = {proj0, t25};
  list<shared_ptr<Op> > db6 = {proj0, t26};
  list<shared_ptr<Op> > db7 = {proj0, t27};
  list<shared_ptr<Op> > db8 = {proj1, t20};
  list<shared_ptr<Op> > db9 = {proj1, t21};
  list<shared_ptr<Op> > db10 = {proj1, t22};
  list<shared_ptr<Op> > db11 = {proj1, t23};
  list<shared_ptr<Op> > db12 = {proj1, t24};
  list<shared_ptr<Op> > db13 = {proj1, t25};
  list<shared_ptr<Op> > db14 = {proj1, t26};
  list<shared_ptr<Op> > db15 = {proj1, t27};
  list<shared_ptr<Op> > db16 = {proj2, t20};
  list<shared_ptr<Op> > db17 = {proj2, t21};
  list<shared_ptr<Op> > db18 = {proj2, t22};
  list<shared_ptr<Op> > db19 = {proj2, t23};
  list<shared_ptr<Op> > db20 = {proj2, t24};
  list<shared_ptr<Op> > db21 = {proj2, t25};
  list<shared_ptr<Op> > db22 = {proj2, t26};
  list<shared_ptr<Op> > db23 = {proj2, t27};
  list<shared_ptr<Op> > db24 = {proj3, t20};
  list<shared_ptr<Op> > db25 = {proj3, t21};
  list<shared_ptr<Op> > db26 = {proj3, t22};
  list<shared_ptr<Op> > db27 = {proj3, t23};
  list<shared_ptr<Op> > db28 = {proj3, t24};
  list<shared_ptr<Op> > db29 = {proj3, t25};
  list<shared_ptr<Op> > db30 = {proj3, t26};
  list<shared_ptr<Op> > db31 = {proj3, t27};
  list<shared_ptr<Op> > db32 = {proj4, t20};
  list<shared_ptr<Op> > db33 = {proj4, t21};
  list<shared_ptr<Op> > db34 = {proj4, t22};
  list<shared_ptr<Op> > db35 = {proj4, t23};
  list<shared_ptr<Op> > db36 = {proj4, t24};
  list<shared_ptr<Op> > db37 = {proj4, t25};
  list<shared_ptr<Op> > db38 = {proj4, t26};
  list<shared_ptr<Op> > db39 = {proj4, t27};
  list<shared_ptr<Op> > db40 = {proj5, t20};
  list<shared_ptr<Op> > db41 = {proj5, t21};
  list<shared_ptr<Op> > db42 = {proj5, t22};
  list<shared_ptr<Op> > db43 = {proj5, t23};
  list<shared_ptr<Op> > db44 = {proj5, t24};
  list<shared_ptr<Op> > db45 = {proj5, t25};
  list<shared_ptr<Op> > db46 = {proj5, t26};
  list<shared_ptr<Op> > db47 = {proj5, t27};
  list<shared_ptr<Op> > db48 = {proj6, t20};
  list<shared_ptr<Op> > db49 = {proj6, t21};
  list<shared_ptr<Op> > db50 = {proj6, t22};
  list<shared_ptr<Op> > db51 = {proj6, t23};
  list<shared_ptr<Op> > db52 = {proj6, t24};
  list<shared_ptr<Op> > db53 = {proj6, t25};
  list<shared_ptr<Op> > db54 = {proj6, t26};
  list<shared_ptr<Op> > db55 = {proj6, t27};
  list<shared_ptr<Op> > db56 = {proj7, t20};
  list<shared_ptr<Op> > db57 = {proj7, t21};
  list<shared_ptr<Op> > db58 = {proj7, t22};
  list<shared_ptr<Op> > db59 = {proj7, t23};
  list<shared_ptr<Op> > db60 = {proj7, t24};
  list<shared_ptr<Op> > db61 = {proj7, t25};
  list<shared_ptr<Op> > db62 = {proj7, t26};
  list<shared_ptr<Op> > db63 = {proj7, t27};
  list<shared_ptr<Op> > dc0 = {proj0, v2};
  list<shared_ptr<Op> > dc1 = {proj1, v2};
  list<shared_ptr<Op> > dc2 = {proj2, v2};
  list<shared_ptr<Op> > dc3 = {proj3, v2};
  list<shared_ptr<Op> > dc4 = {proj4, v2};
  list<shared_ptr<Op> > dc5 = {proj5, v2};
  list<shared_ptr<Op> > dc6 = {proj6, v2};
  list<shared_ptr<Op> > dc7 = {proj7, v2};
  shared_ptr<Diagram> dda0(new Diagram(da0));
  shared_ptr<Diagram> dda1(new Diagram(da1));
  shared_ptr<Diagram> dda2(new Diagram(da2));
  shared_ptr<Diagram> dda3(new Diagram(da3));
  shared_ptr<Diagram> dda4(new Diagram(da4));
  shared_ptr<Diagram> dda5(new Diagram(da5));
  shared_ptr<Diagram> dda6(new Diagram(da6));
  shared_ptr<Diagram> dda7(new Diagram(da7));
  shared_ptr<Diagram> dda8(new Diagram(da8));
  shared_ptr<Diagram> dda9(new Diagram(da9));
  shared_ptr<Diagram> dda10(new Diagram(da10));
  shared_ptr<Diagram> dda11(new Diagram(da11));
  shared_ptr<Diagram> dda12(new Diagram(da12));
  shared_ptr<Diagram> dda13(new Diagram(da13));
  shared_ptr<Diagram> dda14(new Diagram(da14));
  shared_ptr<Diagram> dda15(new Diagram(da15));
  shared_ptr<Diagram> dda16(new Diagram(da16));
  shared_ptr<Diagram> dda17(new Diagram(da17));
  shared_ptr<Diagram> dda18(new Diagram(da18));
  shared_ptr<Diagram> dda19(new Diagram(da19));
  shared_ptr<Diagram> dda20(new Diagram(da20));
  shared_ptr<Diagram> dda21(new Diagram(da21));
  shared_ptr<Diagram> dda22(new Diagram(da22));
  shared_ptr<Diagram> dda23(new Diagram(da23));
  shared_ptr<Diagram> dda24(new Diagram(da24));
  shared_ptr<Diagram> dda25(new Diagram(da25));
  shared_ptr<Diagram> dda26(new Diagram(da26));
  shared_ptr<Diagram> dda27(new Diagram(da27));
  shared_ptr<Diagram> dda28(new Diagram(da28));
  shared_ptr<Diagram> dda29(new Diagram(da29));
  shared_ptr<Diagram> dda30(new Diagram(da30));
  shared_ptr<Diagram> dda31(new Diagram(da31));
  shared_ptr<Diagram> dda32(new Diagram(da32));
  shared_ptr<Diagram> dda33(new Diagram(da33));
  shared_ptr<Diagram> dda34(new Diagram(da34));
  shared_ptr<Diagram> dda35(new Diagram(da35));
  shared_ptr<Diagram> dda36(new Diagram(da36));
  shared_ptr<Diagram> dda37(new Diagram(da37));
  shared_ptr<Diagram> dda38(new Diagram(da38));
  shared_ptr<Diagram> dda39(new Diagram(da39));
  shared_ptr<Diagram> dda40(new Diagram(da40));
  shared_ptr<Diagram> dda41(new Diagram(da41));
  shared_ptr<Diagram> dda42(new Diagram(da42));
  shared_ptr<Diagram> dda43(new Diagram(da43));
  shared_ptr<Diagram> dda44(new Diagram(da44));
  shared_ptr<Diagram> dda45(new Diagram(da45));
  shared_ptr<Diagram> dda46(new Diagram(da46));
  shared_ptr<Diagram> dda47(new Diagram(da47));
  shared_ptr<Diagram> dda48(new Diagram(da48));
  shared_ptr<Diagram> dda49(new Diagram(da49));
  shared_ptr<Diagram> dda50(new Diagram(da50));
  shared_ptr<Diagram> dda51(new Diagram(da51));
  shared_ptr<Diagram> dda52(new Diagram(da52));
  shared_ptr<Diagram> dda53(new Diagram(da53));
  shared_ptr<Diagram> dda54(new Diagram(da54));
  shared_ptr<Diagram> dda55(new Diagram(da55));
  shared_ptr<Diagram> dda56(new Diagram(da56));
  shared_ptr<Diagram> dda57(new Diagram(da57));
  shared_ptr<Diagram> dda58(new Diagram(da58));
  shared_ptr<Diagram> dda59(new Diagram(da59));
  shared_ptr<Diagram> dda60(new Diagram(da60));
  shared_ptr<Diagram> dda61(new Diagram(da61));
  shared_ptr<Diagram> dda62(new Diagram(da62));
  shared_ptr<Diagram> dda63(new Diagram(da63));
  shared_ptr<Diagram> ddb0(new Diagram(db0, "e0"));
  shared_ptr<Diagram> ddb1(new Diagram(db1, "e0"));
  shared_ptr<Diagram> ddb2(new Diagram(db2, "e0"));
  shared_ptr<Diagram> ddb3(new Diagram(db3, "e0"));
  shared_ptr<Diagram> ddb4(new Diagram(db4, "e0"));
  shared_ptr<Diagram> ddb5(new Diagram(db5, "e0"));
  shared_ptr<Diagram> ddb6(new Diagram(db6, "e0"));
  shared_ptr<Diagram> ddb7(new Diagram(db7, "e0"));
  shared_ptr<Diagram> ddb8(new Diagram(db8, "e0"));
  shared_ptr<Diagram> ddb9(new Diagram(db9, "e0"));
  shared_ptr<Diagram> ddb10(new Diagram(db10, "e0"));
  shared_ptr<Diagram> ddb11(new Diagram(db11, "e0"));
  shared_ptr<Diagram> ddb12(new Diagram(db12, "e0"));
  shared_ptr<Diagram> ddb13(new Diagram(db13, "e0"));
  shared_ptr<Diagram> ddb14(new Diagram(db14, "e0"));
  shared_ptr<Diagram> ddb15(new Diagram(db15, "e0"));
  shared_ptr<Diagram> ddb16(new Diagram(db16, "e0"));
  shared_ptr<Diagram> ddb17(new Diagram(db17, "e0"));
  shared_ptr<Diagram> ddb18(new Diagram(db18, "e0"));
  shared_ptr<Diagram> ddb19(new Diagram(db19, "e0"));
  shared_ptr<Diagram> ddb20(new Diagram(db20, "e0"));
  shared_ptr<Diagram> ddb21(new Diagram(db21, "e0"));
  shared_ptr<Diagram> ddb22(new Diagram(db22, "e0"));
  shared_ptr<Diagram> ddb23(new Diagram(db23, "e0"));
  shared_ptr<Diagram> ddb24(new Diagram(db24, "e0"));
  shared_ptr<Diagram> ddb25(new Diagram(db25, "e0"));
  shared_ptr<Diagram> ddb26(new Diagram(db26, "e0"));
  shared_ptr<Diagram> ddb27(new Diagram(db27, "e0"));
  shared_ptr<Diagram> ddb28(new Diagram(db28, "e0"));
  shared_ptr<Diagram> ddb29(new Diagram(db29, "e0"));
  shared_ptr<Diagram> ddb30(new Diagram(db30, "e0"));
  shared_ptr<Diagram> ddb31(new Diagram(db31, "e0"));
  shared_ptr<Diagram> ddb32(new Diagram(db32, "e0"));
  shared_ptr<Diagram> ddb33(new Diagram(db33, "e0"));
  shared_ptr<Diagram> ddb34(new Diagram(db34, "e0"));
  shared_ptr<Diagram> ddb35(new Diagram(db35, "e0"));
  shared_ptr<Diagram> ddb36(new Diagram(db36, "e0"));
  shared_ptr<Diagram> ddb37(new Diagram(db37, "e0"));
  shared_ptr<Diagram> ddb38(new Diagram(db38, "e0"));
  shared_ptr<Diagram> ddb39(new Diagram(db39, "e0"));
  shared_ptr<Diagram> ddb40(new Diagram(db40, "e0"));
  shared_ptr<Diagram> ddb41(new Diagram(db41, "e0"));
  shared_ptr<Diagram> ddb42(new Diagram(db42, "e0"));
  shared_ptr<Diagram> ddb43(new Diagram(db43, "e0"));
  shared_ptr<Diagram> ddb44(new Diagram(db44, "e0"));
  shared_ptr<Diagram> ddb45(new Diagram(db45, "e0"));
  shared_ptr<Diagram> ddb46(new Diagram(db46, "e0"));
  shared_ptr<Diagram> ddb47(new Diagram(db47, "e0"));
  shared_ptr<Diagram> ddb48(new Diagram(db48, "e0"));
  shared_ptr<Diagram> ddb49(new Diagram(db49, "e0"));
  shared_ptr<Diagram> ddb50(new Diagram(db50, "e0"));
  shared_ptr<Diagram> ddb51(new Diagram(db51, "e0"));
  shared_ptr<Diagram> ddb52(new Diagram(db52, "e0"));
  shared_ptr<Diagram> ddb53(new Diagram(db53, "e0"));
  shared_ptr<Diagram> ddb54(new Diagram(db54, "e0"));
  shared_ptr<Diagram> ddb55(new Diagram(db55, "e0"));
  shared_ptr<Diagram> ddb56(new Diagram(db56, "e0"));
  shared_ptr<Diagram> ddb57(new Diagram(db57, "e0"));
  shared_ptr<Diagram> ddb58(new Diagram(db58, "e0"));
  shared_ptr<Diagram> ddb59(new Diagram(db59, "e0"));
  shared_ptr<Diagram> ddb60(new Diagram(db60, "e0"));
  shared_ptr<Diagram> ddb61(new Diagram(db61, "e0"));
  shared_ptr<Diagram> ddb62(new Diagram(db62, "e0"));
  shared_ptr<Diagram> ddb63(new Diagram(db63, "e0"));
  shared_ptr<Diagram> ddc0(new Diagram(dc0));
  shared_ptr<Diagram> ddc1(new Diagram(dc1));
  shared_ptr<Diagram> ddc2(new Diagram(dc2));
  shared_ptr<Diagram> ddc3(new Diagram(dc3));
  shared_ptr<Diagram> ddc4(new Diagram(dc4));
  shared_ptr<Diagram> ddc5(new Diagram(dc5));
  shared_ptr<Diagram> ddc6(new Diagram(dc6));
  shared_ptr<Diagram> ddc7(new Diagram(dc7));
  shared_ptr<Equation> eda0(new Equation(dda0, theory));
  shared_ptr<Equation> eda1(new Equation(dda1, theory));
  shared_ptr<Equation> eda2(new Equation(dda2, theory));
  shared_ptr<Equation> eda3(new Equation(dda3, theory));
  shared_ptr<Equation> eda4(new Equation(dda4, theory));
  shared_ptr<Equation> eda5(new Equation(dda5, theory));
  shared_ptr<Equation> eda6(new Equation(dda6, theory));
  shared_ptr<Equation> eda7(new Equation(dda7, theory));
  shared_ptr<Equation> eda8(new Equation(dda8, theory));
  shared_ptr<Equation> eda9(new Equation(dda9, theory));
  shared_ptr<Equation> eda10(new Equation(dda10, theory));
  shared_ptr<Equation> eda11(new Equation(dda11, theory));
  shared_ptr<Equation> eda12(new Equation(dda12, theory));
  shared_ptr<Equation> eda13(new Equation(dda13, theory));
  shared_ptr<Equation> eda14(new Equation(dda14, theory));
  shared_ptr<Equation> eda15(new Equation(dda15, theory));
  shared_ptr<Equation> eda16(new Equation(dda16, theory));
  shared_ptr<Equation> eda17(new Equation(dda17, theory));
  shared_ptr<Equation> eda18(new Equation(dda18, theory));
  shared_ptr<Equation> eda19(new Equation(dda19, theory));
  shared_ptr<Equation> eda20(new Equation(dda20, theory));
  shared_ptr<Equation> eda21(new Equation(dda21, theory));
  shared_ptr<Equation> eda22(new Equation(dda22, theory));
  shared_ptr<Equation> eda23(new Equation(dda23, theory));
  shared_ptr<Equation> eda24(new Equation(dda24, theory));
  shared_ptr<Equation> eda25(new Equation(dda25, theory));
  shared_ptr<Equation> eda26(new Equation(dda26, theory));
  shared_ptr<Equation> eda27(new Equation(dda27, theory));
  shared_ptr<Equation> eda28(new Equation(dda28, theory));
  shared_ptr<Equation> eda29(new Equation(dda29, theory));
  shared_ptr<Equation> eda30(new Equation(dda30, theory));
  shared_ptr<Equation> eda31(new Equation(dda31, theory));
  shared_ptr<Equation> eda32(new Equation(dda32, theory));
  shared_ptr<Equation> eda33(new Equation(dda33, theory));
  shared_ptr<Equation> eda34(new Equation(dda34, theory));
  shared_ptr<Equation> eda35(new Equation(dda35, theory));
  shared_ptr<Equation> eda36(new Equation(dda36, theory));
  shared_ptr<Equation> eda37(new Equation(dda37, theory));
  shared_ptr<Equation> eda38(new Equation(dda38, theory));
  shared_ptr<Equation> eda39(new Equation(dda39, theory));
  shared_ptr<Equation> eda40(new Equation(dda40, theory));
  shared_ptr<Equation> eda41(new Equation(dda41, theory));
  shared_ptr<Equation> eda42(new Equation(dda42, theory));
  shared_ptr<Equation> eda43(new Equation(dda43, theory));
  shared_ptr<Equation> eda44(new Equation(dda44, theory));
  shared_ptr<Equation> eda45(new Equation(dda45, theory));
  shared_ptr<Equation> eda46(new Equation(dda46, theory));
  shared_ptr<Equation> eda47(new Equation(dda47, theory));
  shared_ptr<Equation> eda48(new Equation(dda48, theory));
  shared_ptr<Equation> eda49(new Equation(dda49, theory));
  shared_ptr<Equation> eda50(new Equation(dda50, theory));
  shared_ptr<Equation> eda51(new Equation(dda51, theory));
  shared_ptr<Equation> eda52(new Equation(dda52, theory));
  shared_ptr<Equation> eda53(new Equation(dda53, theory));
  shared_ptr<Equation> eda54(new Equation(dda54, theory));
  shared_ptr<Equation> eda55(new Equation(dda55, theory));
  shared_ptr<Equation> eda56(new Equation(dda56, theory));
  shared_ptr<Equation> eda57(new Equation(dda57, theory));
  shared_ptr<Equation> eda58(new Equation(dda58, theory));
  shared_ptr<Equation> eda59(new Equation(dda59, theory));
  shared_ptr<Equation> eda60(new Equation(dda60, theory));
  shared_ptr<Equation> eda61(new Equation(dda61, theory));
  shared_ptr<Equation> eda62(new Equation(dda62, theory));
  shared_ptr<Equation> eda63(new Equation(dda63, theory));
  shared_ptr<Equation> edb0(new Equation(ddb0, theory));
  shared_ptr<Equation> edb1(new Equation(ddb1, theory));
  shared_ptr<Equation> edb2(new Equation(ddb2, theory));
  shared_ptr<Equation> edb3(new Equation(ddb3, theory));
  shared_ptr<Equation> edb4(new Equation(ddb4, theory));
  shared_ptr<Equation> edb5(new Equation(ddb5, theory));
  shared_ptr<Equation> edb6(new Equation(ddb6, theory));
  shared_ptr<Equation> edb7(new Equation(ddb7, theory));
  shared_ptr<Equation> edb8(new Equation(ddb8, theory));
  shared_ptr<Equation> edb9(new Equation(ddb9, theory));
  shared_ptr<Equation> edb10(new Equation(ddb10, theory));
  shared_ptr<Equation> edb11(new Equation(ddb11, theory));
  shared_ptr<Equation> edb12(new Equation(ddb12, theory));
  shared_ptr<Equation> edb13(new Equation(ddb13, theory));
  shared_ptr<Equation> edb14(new Equation(ddb14, theory));
  shared_ptr<Equation> edb15(new Equation(ddb15, theory));
  shared_ptr<Equation> edb16(new Equation(ddb16, theory));
  shared_ptr<Equation> edb17(new Equation(ddb17, theory));
  shared_ptr<Equation> edb18(new Equation(ddb18, theory));
  shared_ptr<Equation> edb19(new Equation(ddb19, theory));
  shared_ptr<Equation> edb20(new Equation(ddb20, theory));
  shared_ptr<Equation> edb21(new Equation(ddb21, theory));
  shared_ptr<Equation> edb22(new Equation(ddb22, theory));
  shared_ptr<Equation> edb23(new Equation(ddb23, theory));
  shared_ptr<Equation> edb24(new Equation(ddb24, theory));
  shared_ptr<Equation> edb25(new Equation(ddb25, theory));
  shared_ptr<Equation> edb26(new Equation(ddb26, theory));
  shared_ptr<Equation> edb27(new Equation(ddb27, theory));
  shared_ptr<Equation> edb28(new Equation(ddb28, theory));
  shared_ptr<Equation> edb29(new Equation(ddb29, theory));
  shared_ptr<Equation> edb30(new Equation(ddb30, theory));
  shared_ptr<Equation> edb31(new Equation(ddb31, theory));
  shared_ptr<Equation> edb32(new Equation(ddb32, theory));
  shared_ptr<Equation> edb33(new Equation(ddb33, theory));
  shared_ptr<Equation> edb34(new Equation(ddb34, theory));
  shared_ptr<Equation> edb35(new Equation(ddb35, theory));
  shared_ptr<Equation> edb36(new Equation(ddb36, theory));
  shared_ptr<Equation> edb37(new Equation(ddb37, theory));
  shared_ptr<Equation> edb38(new Equation(ddb38, theory));
  shared_ptr<Equation> edb39(new Equation(ddb39, theory));
  shared_ptr<Equation> edb40(new Equation(ddb40, theory));
  shared_ptr<Equation> edb41(new Equation(ddb41, theory));
  shared_ptr<Equation> edb42(new Equation(ddb42, theory));
  shared_ptr<Equation> edb43(new Equation(ddb43, theory));
  shared_ptr<Equation> edb44(new Equation(ddb44, theory));
  shared_ptr<Equation> edb45(new Equation(ddb45, theory));
  shared_ptr<Equation> edb46(new Equation(ddb46, theory));
  shared_ptr<Equation> edb47(new Equation(ddb47, theory));
  shared_ptr<Equation> edb48(new Equation(ddb48, theory));
  shared_ptr<Equation> edb49(new Equation(ddb49, theory));
  shared_ptr<Equation> edb50(new Equation(ddb50, theory));
  shared_ptr<Equation> edb51(new Equation(ddb51, theory));
  shared_ptr<Equation> edb52(new Equation(ddb52, theory));
  shared_ptr<Equation> edb53(new Equation(ddb53, theory));
  shared_ptr<Equation> edb54(new Equation(ddb54, theory));
  shared_ptr<Equation> edb55(new Equation(ddb55, theory));
  shared_ptr<Equation> edb56(new Equation(ddb56, theory));
  shared_ptr<Equation> edb57(new Equation(ddb57, theory));
  shared_ptr<Equation> edb58(new Equation(ddb58, theory));
  shared_ptr<Equation> edb59(new Equation(ddb59, theory));
  shared_ptr<Equation> edb60(new Equation(ddb60, theory));
  shared_ptr<Equation> edb61(new Equation(ddb61, theory));
  shared_ptr<Equation> edb62(new Equation(ddb62, theory));
  shared_ptr<Equation> edb63(new Equation(ddb63, theory));
  shared_ptr<Equation> edc0(new Equation(ddc0, theory));
  shared_ptr<Equation> edc1(new Equation(ddc1, theory));
  shared_ptr<Equation> edc2(new Equation(ddc2, theory));
  shared_ptr<Equation> edc3(new Equation(ddc3, theory));
  shared_ptr<Equation> edc4(new Equation(ddc4, theory));
  shared_ptr<Equation> edc5(new Equation(ddc5, theory));
  shared_ptr<Equation> edc6(new Equation(ddc6, theory));
  shared_ptr<Equation> edc7(new Equation(ddc7, theory));
  eda0->merge(eda1);
  eda0->merge(eda2);
  eda0->merge(eda3);
  eda0->merge(eda4);
  eda0->merge(eda5);
  eda0->merge(eda6);
  eda0->merge(eda7);
  eda0->merge(eda8);
  eda0->merge(eda9);
  eda0->merge(eda10);
  eda0->merge(eda11);
  eda0->merge(eda12);
  eda0->merge(eda13);
  eda0->merge(eda14);
  eda0->merge(eda15);
  eda0->merge(eda16);
  eda0->merge(eda17);
  eda0->merge(eda18);
  eda0->merge(eda19);
  eda0->merge(eda20);
  eda0->merge(eda21);
  eda0->merge(eda22);
  eda0->merge(eda23);
  eda0->merge(eda24);
  eda0->merge(eda25);
  eda0->merge(eda26);
  eda0->merge(eda27);
  eda0->merge(eda28);
  eda0->merge(eda29);
  eda0->merge(eda30);
  eda0->merge(eda31);
  eda0->merge(eda32);
  eda0->merge(eda33);
  eda0->merge(eda34);
  eda0->merge(eda35);
  eda0->merge(eda36);
  eda0->merge(eda37);
  eda0->merge(eda38);
  eda0->merge(eda39);
  eda0->merge(eda40);
  eda0->merge(eda41);
  eda0->merge(eda42);
  eda0->merge(eda43);
  eda0->merge(eda44);
  eda0->merge(eda45);
  eda0->merge(eda46);
  eda0->merge(eda47);
  eda0->merge(eda48);
  eda0->merge(eda49);
  eda0->merge(eda50);
  eda0->merge(eda51);
  eda0->merge(eda52);
  eda0->merge(eda53);
  eda0->merge(eda54);
  eda0->merge(eda55);
  eda0->merge(eda56);
  eda0->merge(eda57);
  eda0->merge(eda58);
  eda0->merge(eda59);
  eda0->merge(eda60);
  eda0->merge(eda61);
  eda0->merge(eda62);
  eda0->merge(eda63);
  eda0->merge(edb0);
  eda0->merge(edb1);
  eda0->merge(edb2);
  eda0->merge(edb3);
  eda0->merge(edb4);
  eda0->merge(edb5);
  eda0->merge(edb6);
  eda0->merge(edb7);
  eda0->merge(edb8);
  eda0->merge(edb9);
  eda0->merge(edb10);
  eda0->merge(edb11);
  eda0->merge(edb12);
  eda0->merge(edb13);
  eda0->merge(edb14);
  eda0->merge(edb15);
  eda0->merge(edb16);
  eda0->merge(edb17);
  eda0->merge(edb18);
  eda0->merge(edb19);
  eda0->merge(edb20);
  eda0->merge(edb21);
  eda0->merge(edb22);
  eda0->merge(edb23);
  eda0->merge(edb24);
  eda0->merge(edb25);
  eda0->merge(edb26);
  eda0->merge(edb27);
  eda0->merge(edb28);
  eda0->merge(edb29);
  eda0->merge(edb30);
  eda0->merge(edb31);
  eda0->merge(edb32);
  eda0->merge(edb33);
  eda0->merge(edb34);
  eda0->merge(edb35);
  eda0->merge(edb36);
  eda0->merge(edb37);
  eda0->merge(edb38);
  eda0->merge(edb39);
  eda0->merge(edb40);
  eda0->merge(edb41);
  eda0->merge(edb42);
  eda0->merge(edb43);
  eda0->merge(edb44);
  eda0->merge(edb45);
  eda0->merge(edb46);
  eda0->merge(edb47);
  eda0->merge(edb48);
  eda0->merge(edb49);
  eda0->merge(edb50);
  eda0->merge(edb51);
  eda0->merge(edb52);
  eda0->merge(edb53);
  eda0->merge(edb54);
  eda0->merge(edb55);
  eda0->merge(edb56);
  eda0->merge(edb57);
  eda0->merge(edb58);
  eda0->merge(edb59);
  eda0->merge(edb60);
  eda0->merge(edb61);
  eda0->merge(edb62);
  eda0->merge(edb63);
  eda0->merge(edc0);
  eda0->merge(edc1);
  eda0->merge(edc2);
  eda0->merge(edc3);
  eda0->merge(edc4);
  eda0->merge(edc5);
  eda0->merge(edc6);
  eda0->merge(edc7);
  eda0->duplicates();
  eda0->active();
  shared_ptr<Tree> tda(new Tree(eda0));
  tda->sort_gamma();
  list<shared_ptr<Op> > ea0 = {proje, t2dagger0, v2};
  list<shared_ptr<Op> > ea1 = {proje, t2dagger1, v2};
  list<shared_ptr<Op> > ea2 = {proje, t2dagger2, v2};
  list<shared_ptr<Op> > ea3 = {proje, t2dagger3, v2};
  list<shared_ptr<Op> > ea4 = {proje, t2dagger4, v2};
  list<shared_ptr<Op> > ea5 = {proje, t2dagger5, v2};
  list<shared_ptr<Op> > ea6 = {proje, t2dagger6, v2};
  list<shared_ptr<Op> > ea7 = {proje, t2dagger7, v2};
  list<shared_ptr<Op> > eb0 = {proje, t2dagger0, r0};
  list<shared_ptr<Op> > eb1 = {proje, t2dagger0, r1};
  list<shared_ptr<Op> > eb2 = {proje, t2dagger0, r2};
  list<shared_ptr<Op> > eb3 = {proje, t2dagger0, r3};
  list<shared_ptr<Op> > eb4 = {proje, t2dagger0, r4};
  list<shared_ptr<Op> > eb5 = {proje, t2dagger0, r5};
  list<shared_ptr<Op> > eb6 = {proje, t2dagger0, r6};
  list<shared_ptr<Op> > eb7 = {proje, t2dagger0, r7};
  list<shared_ptr<Op> > eb8 = {proje, t2dagger1, r0};
  list<shared_ptr<Op> > eb9 = {proje, t2dagger1, r1};
  list<shared_ptr<Op> > eb10 = {proje, t2dagger1, r2};
  list<shared_ptr<Op> > eb11 = {proje, t2dagger1, r3};
  list<shared_ptr<Op> > eb12 = {proje, t2dagger1, r4};
  list<shared_ptr<Op> > eb13 = {proje, t2dagger1, r5};
  list<shared_ptr<Op> > eb14 = {proje, t2dagger1, r6};
  list<shared_ptr<Op> > eb15 = {proje, t2dagger1, r7};
  list<shared_ptr<Op> > eb16 = {proje, t2dagger2, r0};
  list<shared_ptr<Op> > eb17 = {proje, t2dagger2, r1};
  list<shared_ptr<Op> > eb18 = {proje, t2dagger2, r2};
  list<shared_ptr<Op> > eb19 = {proje, t2dagger2, r3};
  list<shared_ptr<Op> > eb20 = {proje, t2dagger2, r4};
  list<shared_ptr<Op> > eb21 = {proje, t2dagger2, r5};
  list<shared_ptr<Op> > eb22 = {proje, t2dagger2, r6};
  list<shared_ptr<Op> > eb23 = {proje, t2dagger2, r7};
  list<shared_ptr<Op> > eb24 = {proje, t2dagger3, r0};
  list<shared_ptr<Op> > eb25 = {proje, t2dagger3, r1};
  list<shared_ptr<Op> > eb26 = {proje, t2dagger3, r2};
  list<shared_ptr<Op> > eb27 = {proje, t2dagger3, r3};
  list<shared_ptr<Op> > eb28 = {proje, t2dagger3, r4};
  list<shared_ptr<Op> > eb29 = {proje, t2dagger3, r5};
  list<shared_ptr<Op> > eb30 = {proje, t2dagger3, r6};
  list<shared_ptr<Op> > eb31 = {proje, t2dagger3, r7};
  list<shared_ptr<Op> > eb32 = {proje, t2dagger4, r0};
  list<shared_ptr<Op> > eb33 = {proje, t2dagger4, r1};
  list<shared_ptr<Op> > eb34 = {proje, t2dagger4, r2};
  list<shared_ptr<Op> > eb35 = {proje, t2dagger4, r3};
  list<shared_ptr<Op> > eb36 = {proje, t2dagger4, r4};
  list<shared_ptr<Op> > eb37 = {proje, t2dagger4, r5};
  list<shared_ptr<Op> > eb38 = {proje, t2dagger4, r6};
  list<shared_ptr<Op> > eb39 = {proje, t2dagger4, r7};
  list<shared_ptr<Op> > eb40 = {proje, t2dagger5, r0};
  list<shared_ptr<Op> > eb41 = {proje, t2dagger5, r1};
  list<shared_ptr<Op> > eb42 = {proje, t2dagger5, r2};
  list<shared_ptr<Op> > eb43 = {proje, t2dagger5, r3};
  list<shared_ptr<Op> > eb44 = {proje, t2dagger5, r4};
  list<shared_ptr<Op> > eb45 = {proje, t2dagger5, r5};
  list<shared_ptr<Op> > eb46 = {proje, t2dagger5, r6};
  list<shared_ptr<Op> > eb47 = {proje, t2dagger5, r7};
  list<shared_ptr<Op> > eb48 = {proje, t2dagger6, r0};
  list<shared_ptr<Op> > eb49 = {proje, t2dagger6, r1};
  list<shared_ptr<Op> > eb50 = {proje, t2dagger6, r2};
  list<shared_ptr<Op> > eb51 = {proje, t2dagger6, r3};
  list<shared_ptr<Op> > eb52 = {proje, t2dagger6, r4};
  list<shared_ptr<Op> > eb53 = {proje, t2dagger6, r5};
  list<shared_ptr<Op> > eb54 = {proje, t2dagger6, r6};
  list<shared_ptr<Op> > eb55 = {proje, t2dagger6, r7};
  list<shared_ptr<Op> > eb56 = {proje, t2dagger7, r0};
  list<shared_ptr<Op> > eb57 = {proje, t2dagger7, r1};
  list<shared_ptr<Op> > eb58 = {proje, t2dagger7, r2};
  list<shared_ptr<Op> > eb59 = {proje, t2dagger7, r3};
  list<shared_ptr<Op> > eb60 = {proje, t2dagger7, r4};
  list<shared_ptr<Op> > eb61 = {proje, t2dagger7, r5};
  list<shared_ptr<Op> > eb62 = {proje, t2dagger7, r6};
  list<shared_ptr<Op> > eb63 = {proje, t2dagger7, r7};
  shared_ptr<Diagram> dea0(new Diagram(ea0));
  shared_ptr<Diagram> dea1(new Diagram(ea1));
  shared_ptr<Diagram> dea2(new Diagram(ea2));
  shared_ptr<Diagram> dea3(new Diagram(ea3));
  shared_ptr<Diagram> dea4(new Diagram(ea4));
  shared_ptr<Diagram> dea5(new Diagram(ea5));
  shared_ptr<Diagram> dea6(new Diagram(ea6));
  shared_ptr<Diagram> dea7(new Diagram(ea7));
  shared_ptr<Diagram> deb0(new Diagram(eb0));
  shared_ptr<Diagram> deb1(new Diagram(eb1));
  shared_ptr<Diagram> deb2(new Diagram(eb2));
  shared_ptr<Diagram> deb3(new Diagram(eb3));
  shared_ptr<Diagram> deb4(new Diagram(eb4));
  shared_ptr<Diagram> deb5(new Diagram(eb5));
  shared_ptr<Diagram> deb6(new Diagram(eb6));
  shared_ptr<Diagram> deb7(new Diagram(eb7));
  shared_ptr<Diagram> deb8(new Diagram(eb8));
  shared_ptr<Diagram> deb9(new Diagram(eb9));
  shared_ptr<Diagram> deb10(new Diagram(eb10));
  shared_ptr<Diagram> deb11(new Diagram(eb11));
  shared_ptr<Diagram> deb12(new Diagram(eb12));
  shared_ptr<Diagram> deb13(new Diagram(eb13));
  shared_ptr<Diagram> deb14(new Diagram(eb14));
  shared_ptr<Diagram> deb15(new Diagram(eb15));
  shared_ptr<Diagram> deb16(new Diagram(eb16));
  shared_ptr<Diagram> deb17(new Diagram(eb17));
  shared_ptr<Diagram> deb18(new Diagram(eb18));
  shared_ptr<Diagram> deb19(new Diagram(eb19));
  shared_ptr<Diagram> deb20(new Diagram(eb20));
  shared_ptr<Diagram> deb21(new Diagram(eb21));
  shared_ptr<Diagram> deb22(new Diagram(eb22));
  shared_ptr<Diagram> deb23(new Diagram(eb23));
  shared_ptr<Diagram> deb24(new Diagram(eb24));
  shared_ptr<Diagram> deb25(new Diagram(eb25));
  shared_ptr<Diagram> deb26(new Diagram(eb26));
  shared_ptr<Diagram> deb27(new Diagram(eb27));
  shared_ptr<Diagram> deb28(new Diagram(eb28));
  shared_ptr<Diagram> deb29(new Diagram(eb29));
  shared_ptr<Diagram> deb30(new Diagram(eb30));
  shared_ptr<Diagram> deb31(new Diagram(eb31));
  shared_ptr<Diagram> deb32(new Diagram(eb32));
  shared_ptr<Diagram> deb33(new Diagram(eb33));
  shared_ptr<Diagram> deb34(new Diagram(eb34));
  shared_ptr<Diagram> deb35(new Diagram(eb35));
  shared_ptr<Diagram> deb36(new Diagram(eb36));
  shared_ptr<Diagram> deb37(new Diagram(eb37));
  shared_ptr<Diagram> deb38(new Diagram(eb38));
  shared_ptr<Diagram> deb39(new Diagram(eb39));
  shared_ptr<Diagram> deb40(new Diagram(eb40));
  shared_ptr<Diagram> deb41(new Diagram(eb41));
  shared_ptr<Diagram> deb42(new Diagram(eb42));
  shared_ptr<Diagram> deb43(new Diagram(eb43));
  shared_ptr<Diagram> deb44(new Diagram(eb44));
  shared_ptr<Diagram> deb45(new Diagram(eb45));
  shared_ptr<Diagram> deb46(new Diagram(eb46));
  shared_ptr<Diagram> deb47(new Diagram(eb47));
  shared_ptr<Diagram> deb48(new Diagram(eb48));
  shared_ptr<Diagram> deb49(new Diagram(eb49));
  shared_ptr<Diagram> deb50(new Diagram(eb50));
  shared_ptr<Diagram> deb51(new Diagram(eb51));
  shared_ptr<Diagram> deb52(new Diagram(eb52));
  shared_ptr<Diagram> deb53(new Diagram(eb53));
  shared_ptr<Diagram> deb54(new Diagram(eb54));
  shared_ptr<Diagram> deb55(new Diagram(eb55));
  shared_ptr<Diagram> deb56(new Diagram(eb56));
  shared_ptr<Diagram> deb57(new Diagram(eb57));
  shared_ptr<Diagram> deb58(new Diagram(eb58));
  shared_ptr<Diagram> deb59(new Diagram(eb59));
  shared_ptr<Diagram> deb60(new Diagram(eb60));
  shared_ptr<Diagram> deb61(new Diagram(eb61));
  shared_ptr<Diagram> deb62(new Diagram(eb62));
  shared_ptr<Diagram> deb63(new Diagram(eb63));
  shared_ptr<Equation> eea0(new Equation(dea0, theory));
  shared_ptr<Equation> eea1(new Equation(dea1, theory));
  shared_ptr<Equation> eea2(new Equation(dea2, theory));
  shared_ptr<Equation> eea3(new Equation(dea3, theory));
  shared_ptr<Equation> eea4(new Equation(dea4, theory));
  shared_ptr<Equation> eea5(new Equation(dea5, theory));
  shared_ptr<Equation> eea6(new Equation(dea6, theory));
  shared_ptr<Equation> eea7(new Equation(dea7, theory));
  shared_ptr<Equation> eeb0(new Equation(deb0, theory));
  shared_ptr<Equation> eeb1(new Equation(deb1, theory));
  shared_ptr<Equation> eeb2(new Equation(deb2, theory));
  shared_ptr<Equation> eeb3(new Equation(deb3, theory));
  shared_ptr<Equation> eeb4(new Equation(deb4, theory));
  shared_ptr<Equation> eeb5(new Equation(deb5, theory));
  shared_ptr<Equation> eeb6(new Equation(deb6, theory));
  shared_ptr<Equation> eeb7(new Equation(deb7, theory));
  shared_ptr<Equation> eeb8(new Equation(deb8, theory));
  shared_ptr<Equation> eeb9(new Equation(deb9, theory));
  shared_ptr<Equation> eeb10(new Equation(deb10, theory));
  shared_ptr<Equation> eeb11(new Equation(deb11, theory));
  shared_ptr<Equation> eeb12(new Equation(deb12, theory));
  shared_ptr<Equation> eeb13(new Equation(deb13, theory));
  shared_ptr<Equation> eeb14(new Equation(deb14, theory));
  shared_ptr<Equation> eeb15(new Equation(deb15, theory));
  shared_ptr<Equation> eeb16(new Equation(deb16, theory));
  shared_ptr<Equation> eeb17(new Equation(deb17, theory));
  shared_ptr<Equation> eeb18(new Equation(deb18, theory));
  shared_ptr<Equation> eeb19(new Equation(deb19, theory));
  shared_ptr<Equation> eeb20(new Equation(deb20, theory));
  shared_ptr<Equation> eeb21(new Equation(deb21, theory));
  shared_ptr<Equation> eeb22(new Equation(deb22, theory));
  shared_ptr<Equation> eeb23(new Equation(deb23, theory));
  shared_ptr<Equation> eeb24(new Equation(deb24, theory));
  shared_ptr<Equation> eeb25(new Equation(deb25, theory));
  shared_ptr<Equation> eeb26(new Equation(deb26, theory));
  shared_ptr<Equation> eeb27(new Equation(deb27, theory));
  shared_ptr<Equation> eeb28(new Equation(deb28, theory));
  shared_ptr<Equation> eeb29(new Equation(deb29, theory));
  shared_ptr<Equation> eeb30(new Equation(deb30, theory));
  shared_ptr<Equation> eeb31(new Equation(deb31, theory));
  shared_ptr<Equation> eeb32(new Equation(deb32, theory));
  shared_ptr<Equation> eeb33(new Equation(deb33, theory));
  shared_ptr<Equation> eeb34(new Equation(deb34, theory));
  shared_ptr<Equation> eeb35(new Equation(deb35, theory));
  shared_ptr<Equation> eeb36(new Equation(deb36, theory));
  shared_ptr<Equation> eeb37(new Equation(deb37, theory));
  shared_ptr<Equation> eeb38(new Equation(deb38, theory));
  shared_ptr<Equation> eeb39(new Equation(deb39, theory));
  shared_ptr<Equation> eeb40(new Equation(deb40, theory));
  shared_ptr<Equation> eeb41(new Equation(deb41, theory));
  shared_ptr<Equation> eeb42(new Equation(deb42, theory));
  shared_ptr<Equation> eeb43(new Equation(deb43, theory));
  shared_ptr<Equation> eeb44(new Equation(deb44, theory));
  shared_ptr<Equation> eeb45(new Equation(deb45, theory));
  shared_ptr<Equation> eeb46(new Equation(deb46, theory));
  shared_ptr<Equation> eeb47(new Equation(deb47, theory));
  shared_ptr<Equation> eeb48(new Equation(deb48, theory));
  shared_ptr<Equation> eeb49(new Equation(deb49, theory));
  shared_ptr<Equation> eeb50(new Equation(deb50, theory));
  shared_ptr<Equation> eeb51(new Equation(deb51, theory));
  shared_ptr<Equation> eeb52(new Equation(deb52, theory));
  shared_ptr<Equation> eeb53(new Equation(deb53, theory));
  shared_ptr<Equation> eeb54(new Equation(deb54, theory));
  shared_ptr<Equation> eeb55(new Equation(deb55, theory));
  shared_ptr<Equation> eeb56(new Equation(deb56, theory));
  shared_ptr<Equation> eeb57(new Equation(deb57, theory));
  shared_ptr<Equation> eeb58(new Equation(deb58, theory));
  shared_ptr<Equation> eeb59(new Equation(deb59, theory));
  shared_ptr<Equation> eeb60(new Equation(deb60, theory));
  shared_ptr<Equation> eeb61(new Equation(deb61, theory));
  shared_ptr<Equation> eeb62(new Equation(deb62, theory));
  shared_ptr<Equation> eeb63(new Equation(deb63, theory));
  eea0->merge(eea1);
  eea0->merge(eea2);
  eea0->merge(eea3);
  eea0->merge(eea4);
  eea0->merge(eea5);
  eea0->merge(eea6);
  eea0->merge(eea7);
  eea0->merge(eeb0);
  eea0->merge(eeb1);
  eea0->merge(eeb2);
  eea0->merge(eeb3);
  eea0->merge(eeb4);
  eea0->merge(eeb5);
  eea0->merge(eeb6);
  eea0->merge(eeb7);
  eea0->merge(eeb8);
  eea0->merge(eeb9);
  eea0->merge(eeb10);
  eea0->merge(eeb11);
  eea0->merge(eeb12);
  eea0->merge(eeb13);
  eea0->merge(eeb14);
  eea0->merge(eeb15);
  eea0->merge(eeb16);
  eea0->merge(eeb17);
  eea0->merge(eeb18);
  eea0->merge(eeb19);
  eea0->merge(eeb20);
  eea0->merge(eeb21);
  eea0->merge(eeb22);
  eea0->merge(eeb23);
  eea0->merge(eeb24);
  eea0->merge(eeb25);
  eea0->merge(eeb26);
  eea0->merge(eeb27);
  eea0->merge(eeb28);
  eea0->merge(eeb29);
  eea0->merge(eeb30);
  eea0->merge(eeb31);
  eea0->merge(eeb32);
  eea0->merge(eeb33);
  eea0->merge(eeb34);
  eea0->merge(eeb35);
  eea0->merge(eeb36);
  eea0->merge(eeb37);
  eea0->merge(eeb38);
  eea0->merge(eeb39);
  eea0->merge(eeb40);
  eea0->merge(eeb41);
  eea0->merge(eeb42);
  eea0->merge(eeb43);
  eea0->merge(eeb44);
  eea0->merge(eeb45);
  eea0->merge(eeb46);
  eea0->merge(eeb47);
  eea0->merge(eeb48);
  eea0->merge(eeb49);
  eea0->merge(eeb50);
  eea0->merge(eeb51);
  eea0->merge(eeb52);
  eea0->merge(eeb53);
  eea0->merge(eeb54);
  eea0->merge(eeb55);
  eea0->merge(eeb56);
  eea0->merge(eeb57);
  eea0->merge(eeb58);
  eea0->merge(eeb59);
  eea0->merge(eeb60);
  eea0->merge(eeb61);
  eea0->merge(eeb62);
  eea0->merge(eeb63);
  eea0->duplicates();
  eea0->active();
  shared_ptr<Tree> tea(new Tree(eea0));
  tea->sort_gamma(tda->gamma());

  ofstream fs(tda->tree_name() + ".h");
  ofstream es(tda->tree_name() + "_tasks.h");
  pair<string, std::string> tmp = tda->generate_task_list(false, tea);
  fs << tmp.first;
  es << tmp.second;
  fs.close();
  es.close();
  cout << std::endl;

  // output
  cout << std::endl << "   *** Residual ***" << std::endl << std::endl;
  tda->print();
  cout << std::endl << "   ***  Energy  ***" << std::endl << std::endl;
  tea->print();
  cout << std::endl << std::endl;

  return 0;
}

