//
// SMITH3 - generates spin-free multireference electron correlation programs.
// Filename: main.cc
// Copyright (C) 2012 Toru Shiozaki
//
// Author: Toru Shiozaki <shiozaki@northwestern.edu>
// Maintainer: Shiozaki group
//
// This file is part of the SMITH3 package.
//
// The SMITH3 package is free software; you can redistribute it and/or modify
// it under the terms of the GNU Library General Public License as published by
// the Free Software Foundation; either version 2, or (at your option)
// any later version.
//
// The SMITH3 package is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Library General Public License for more details.
//
// You should have received a copy of the GNU Library General Public License
// along with the SMITH3 package; see COPYING.  If not, write to
// the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.
//


// This program is supposed to perform Wick's theorem for multireference problems.
// Spin averaged quantities assumed.

#include <fstream>
#include "constants.h"
#include "forest.h"
#include "residual.h"
#include "energy.h"

using namespace std;
using namespace smith;

int main() {

  string theory="RelCASPT2";

  shared_ptr<Operator> ex_0 = make_shared<Op>(_C, _C, _X, _X);
  shared_ptr<Operator> ex_1 = make_shared<Op>(_X, _C, _X, _X);
  shared_ptr<Operator> ex_2 = make_shared<Op>(_C, _C, _X, _A);
  shared_ptr<Operator> ex_3 = make_shared<Op>(_X, _C, _X, _A);
  shared_ptr<Operator> ex_4 = make_shared<Op>(_C, _X, _X, _A);
  shared_ptr<Operator> ex_5 = make_shared<Op>(_X, _X, _X, _A);
  shared_ptr<Operator> ex_6 = make_shared<Op>(_C, _C, _A, _A);
  shared_ptr<Operator> ex_7 = make_shared<Op>(_X, _C, _A, _A);
  shared_ptr<Operator> ex_8 = make_shared<Op>(_X, _X, _A, _A);
  shared_ptr<Operator> t20 = make_shared<Op>("t2", _X, _X, _C, _C);
  shared_ptr<Operator> t21 = make_shared<Op>("t2", _X, _X, _X, _C);
  shared_ptr<Operator> t22 = make_shared<Op>("t2", _X, _A, _C, _C);
  shared_ptr<Operator> t23 = make_shared<Op>("t2", _X, _A, _X, _C);
  shared_ptr<Operator> t24 = make_shared<Op>("t2", _X, _A, _C, _X);
  shared_ptr<Operator> t25 = make_shared<Op>("t2", _X, _A, _X, _X);
  shared_ptr<Operator> t26 = make_shared<Op>("t2", _A, _A, _C, _C);
  shared_ptr<Operator> t27 = make_shared<Op>("t2", _A, _A, _X, _C);
  shared_ptr<Operator> t28 = make_shared<Op>("t2", _A, _A, _X, _X);
  shared_ptr<Operator> f1 = make_shared<Op>("f1", _G, _G);
  shared_ptr<Operator> v2 = make_shared<Op>("v2", _G, _G, _G, _G);
  shared_ptr<Operator> h1 = make_shared<Op>("h1", _G, _G);
  shared_ptr<Operator> proje = make_shared<Op>("proj");
  shared_ptr<Operator> t2dagger0 = make_shared<Op>("t2dagger", _C, _C, _X, _X);
  shared_ptr<Operator> t2dagger1 = make_shared<Op>("t2dagger", _X, _C, _X, _X);
  shared_ptr<Operator> t2dagger2 = make_shared<Op>("t2dagger", _C, _C, _X, _A);
  shared_ptr<Operator> t2dagger3 = make_shared<Op>("t2dagger", _X, _C, _X, _A);
  shared_ptr<Operator> t2dagger4 = make_shared<Op>("t2dagger", _C, _X, _X, _A);
  shared_ptr<Operator> t2dagger5 = make_shared<Op>("t2dagger", _X, _X, _X, _A);
  shared_ptr<Operator> t2dagger6 = make_shared<Op>("t2dagger", _C, _C, _A, _A);
  shared_ptr<Operator> t2dagger7 = make_shared<Op>("t2dagger", _X, _C, _A, _A);
  shared_ptr<Operator> t2dagger8 = make_shared<Op>("t2dagger", _X, _X, _A, _A);
  shared_ptr<Operator> ex_1b = make_shared<Op>(_G, _G);

  list<shared_ptr<Operator>> ra0 = {proje, ex_0, f1, t20};
  list<shared_ptr<Operator>> ra1 = {proje, ex_0, f1, t21};
  list<shared_ptr<Operator>> ra2 = {proje, ex_0, f1, t22};
  list<shared_ptr<Operator>> ra3 = {proje, ex_0, f1, t23};
  list<shared_ptr<Operator>> ra4 = {proje, ex_0, f1, t24};
  list<shared_ptr<Operator>> ra5 = {proje, ex_0, f1, t25};
  list<shared_ptr<Operator>> ra6 = {proje, ex_0, f1, t26};
  list<shared_ptr<Operator>> ra7 = {proje, ex_0, f1, t27};
  list<shared_ptr<Operator>> ra8 = {proje, ex_0, f1, t28};
  list<shared_ptr<Operator>> ra9 = {proje, ex_1, f1, t20};
  list<shared_ptr<Operator>> ra10 = {proje, ex_1, f1, t21};
  list<shared_ptr<Operator>> ra11 = {proje, ex_1, f1, t22};
  list<shared_ptr<Operator>> ra12 = {proje, ex_1, f1, t23};
  list<shared_ptr<Operator>> ra13 = {proje, ex_1, f1, t24};
  list<shared_ptr<Operator>> ra14 = {proje, ex_1, f1, t25};
  list<shared_ptr<Operator>> ra15 = {proje, ex_1, f1, t26};
  list<shared_ptr<Operator>> ra16 = {proje, ex_1, f1, t27};
  list<shared_ptr<Operator>> ra17 = {proje, ex_1, f1, t28};
  list<shared_ptr<Operator>> ra18 = {proje, ex_2, f1, t20};
  list<shared_ptr<Operator>> ra19 = {proje, ex_2, f1, t21};
  list<shared_ptr<Operator>> ra20 = {proje, ex_2, f1, t22};
  list<shared_ptr<Operator>> ra21 = {proje, ex_2, f1, t23};
  list<shared_ptr<Operator>> ra22 = {proje, ex_2, f1, t24};
  list<shared_ptr<Operator>> ra23 = {proje, ex_2, f1, t25};
  list<shared_ptr<Operator>> ra24 = {proje, ex_2, f1, t26};
  list<shared_ptr<Operator>> ra25 = {proje, ex_2, f1, t27};
  list<shared_ptr<Operator>> ra26 = {proje, ex_2, f1, t28};
  list<shared_ptr<Operator>> ra27 = {proje, ex_3, f1, t20};
  list<shared_ptr<Operator>> ra28 = {proje, ex_3, f1, t21};
  list<shared_ptr<Operator>> ra29 = {proje, ex_3, f1, t22};
  list<shared_ptr<Operator>> ra30 = {proje, ex_3, f1, t23};
  list<shared_ptr<Operator>> ra31 = {proje, ex_3, f1, t24};
  list<shared_ptr<Operator>> ra32 = {proje, ex_3, f1, t25};
  list<shared_ptr<Operator>> ra33 = {proje, ex_3, f1, t26};
  list<shared_ptr<Operator>> ra34 = {proje, ex_3, f1, t27};
  list<shared_ptr<Operator>> ra35 = {proje, ex_3, f1, t28};
  list<shared_ptr<Operator>> ra36 = {proje, ex_4, f1, t20};
  list<shared_ptr<Operator>> ra37 = {proje, ex_4, f1, t21};
  list<shared_ptr<Operator>> ra38 = {proje, ex_4, f1, t22};
  list<shared_ptr<Operator>> ra39 = {proje, ex_4, f1, t23};
  list<shared_ptr<Operator>> ra40 = {proje, ex_4, f1, t24};
  list<shared_ptr<Operator>> ra41 = {proje, ex_4, f1, t25};
  list<shared_ptr<Operator>> ra42 = {proje, ex_4, f1, t26};
  list<shared_ptr<Operator>> ra43 = {proje, ex_4, f1, t27};
  list<shared_ptr<Operator>> ra44 = {proje, ex_4, f1, t28};
  list<shared_ptr<Operator>> ra45 = {proje, ex_5, f1, t20};
  list<shared_ptr<Operator>> ra46 = {proje, ex_5, f1, t21};
  list<shared_ptr<Operator>> ra47 = {proje, ex_5, f1, t22};
  list<shared_ptr<Operator>> ra48 = {proje, ex_5, f1, t23};
  list<shared_ptr<Operator>> ra49 = {proje, ex_5, f1, t24};
  list<shared_ptr<Operator>> ra50 = {proje, ex_5, f1, t25};
  list<shared_ptr<Operator>> ra51 = {proje, ex_5, f1, t26};
  list<shared_ptr<Operator>> ra52 = {proje, ex_5, f1, t27};
  list<shared_ptr<Operator>> ra53 = {proje, ex_5, f1, t28};
  list<shared_ptr<Operator>> ra54 = {proje, ex_6, f1, t20};
  list<shared_ptr<Operator>> ra55 = {proje, ex_6, f1, t21};
  list<shared_ptr<Operator>> ra56 = {proje, ex_6, f1, t22};
  list<shared_ptr<Operator>> ra57 = {proje, ex_6, f1, t23};
  list<shared_ptr<Operator>> ra58 = {proje, ex_6, f1, t24};
  list<shared_ptr<Operator>> ra59 = {proje, ex_6, f1, t25};
  list<shared_ptr<Operator>> ra60 = {proje, ex_6, f1, t27};
  list<shared_ptr<Operator>> ra61 = {proje, ex_6, f1, t28};
  list<shared_ptr<Operator>> ra62 = {proje, ex_7, f1, t20};
  list<shared_ptr<Operator>> ra63 = {proje, ex_7, f1, t21};
  list<shared_ptr<Operator>> ra64 = {proje, ex_7, f1, t22};
  list<shared_ptr<Operator>> ra65 = {proje, ex_7, f1, t23};
  list<shared_ptr<Operator>> ra66 = {proje, ex_7, f1, t24};
  list<shared_ptr<Operator>> ra67 = {proje, ex_7, f1, t25};
  list<shared_ptr<Operator>> ra68 = {proje, ex_7, f1, t26};
  list<shared_ptr<Operator>> ra69 = {proje, ex_7, f1, t27};
  list<shared_ptr<Operator>> ra70 = {proje, ex_7, f1, t28};
  list<shared_ptr<Operator>> ra71 = {proje, ex_8, f1, t20};
  list<shared_ptr<Operator>> ra72 = {proje, ex_8, f1, t21};
  list<shared_ptr<Operator>> ra73 = {proje, ex_8, f1, t22};
  list<shared_ptr<Operator>> ra74 = {proje, ex_8, f1, t23};
  list<shared_ptr<Operator>> ra75 = {proje, ex_8, f1, t24};
  list<shared_ptr<Operator>> ra76 = {proje, ex_8, f1, t25};
  list<shared_ptr<Operator>> ra77 = {proje, ex_8, f1, t26};
  list<shared_ptr<Operator>> ra78 = {proje, ex_8, f1, t27};
  list<shared_ptr<Operator>> ra79 = {proje, ex_8, f1, t28};
  list<shared_ptr<Operator>> rb0 = {proje, ex_0, t20};
  list<shared_ptr<Operator>> rb1 = {proje, ex_0, t21};
  list<shared_ptr<Operator>> rb2 = {proje, ex_0, t22};
  list<shared_ptr<Operator>> rb3 = {proje, ex_0, t23};
  list<shared_ptr<Operator>> rb4 = {proje, ex_0, t24};
  list<shared_ptr<Operator>> rb5 = {proje, ex_0, t25};
  list<shared_ptr<Operator>> rb6 = {proje, ex_0, t26};
  list<shared_ptr<Operator>> rb7 = {proje, ex_0, t27};
  list<shared_ptr<Operator>> rb8 = {proje, ex_0, t28};
  list<shared_ptr<Operator>> rb9 = {proje, ex_1, t20};
  list<shared_ptr<Operator>> rb10 = {proje, ex_1, t21};
  list<shared_ptr<Operator>> rb11 = {proje, ex_1, t22};
  list<shared_ptr<Operator>> rb12 = {proje, ex_1, t23};
  list<shared_ptr<Operator>> rb13 = {proje, ex_1, t24};
  list<shared_ptr<Operator>> rb14 = {proje, ex_1, t25};
  list<shared_ptr<Operator>> rb15 = {proje, ex_1, t26};
  list<shared_ptr<Operator>> rb16 = {proje, ex_1, t27};
  list<shared_ptr<Operator>> rb17 = {proje, ex_1, t28};
  list<shared_ptr<Operator>> rb18 = {proje, ex_2, t20};
  list<shared_ptr<Operator>> rb19 = {proje, ex_2, t21};
  list<shared_ptr<Operator>> rb20 = {proje, ex_2, t22};
  list<shared_ptr<Operator>> rb21 = {proje, ex_2, t23};
  list<shared_ptr<Operator>> rb22 = {proje, ex_2, t24};
  list<shared_ptr<Operator>> rb23 = {proje, ex_2, t25};
  list<shared_ptr<Operator>> rb24 = {proje, ex_2, t26};
  list<shared_ptr<Operator>> rb25 = {proje, ex_2, t27};
  list<shared_ptr<Operator>> rb26 = {proje, ex_2, t28};
  list<shared_ptr<Operator>> rb27 = {proje, ex_3, t20};
  list<shared_ptr<Operator>> rb28 = {proje, ex_3, t21};
  list<shared_ptr<Operator>> rb29 = {proje, ex_3, t22};
  list<shared_ptr<Operator>> rb30 = {proje, ex_3, t23};
  list<shared_ptr<Operator>> rb31 = {proje, ex_3, t24};
  list<shared_ptr<Operator>> rb32 = {proje, ex_3, t25};
  list<shared_ptr<Operator>> rb33 = {proje, ex_3, t26};
  list<shared_ptr<Operator>> rb34 = {proje, ex_3, t27};
  list<shared_ptr<Operator>> rb35 = {proje, ex_3, t28};
  list<shared_ptr<Operator>> rb36 = {proje, ex_4, t20};
  list<shared_ptr<Operator>> rb37 = {proje, ex_4, t21};
  list<shared_ptr<Operator>> rb38 = {proje, ex_4, t22};
  list<shared_ptr<Operator>> rb39 = {proje, ex_4, t23};
  list<shared_ptr<Operator>> rb40 = {proje, ex_4, t24};
  list<shared_ptr<Operator>> rb41 = {proje, ex_4, t25};
  list<shared_ptr<Operator>> rb42 = {proje, ex_4, t26};
  list<shared_ptr<Operator>> rb43 = {proje, ex_4, t27};
  list<shared_ptr<Operator>> rb44 = {proje, ex_4, t28};
  list<shared_ptr<Operator>> rb45 = {proje, ex_5, t20};
  list<shared_ptr<Operator>> rb46 = {proje, ex_5, t21};
  list<shared_ptr<Operator>> rb47 = {proje, ex_5, t22};
  list<shared_ptr<Operator>> rb48 = {proje, ex_5, t23};
  list<shared_ptr<Operator>> rb49 = {proje, ex_5, t24};
  list<shared_ptr<Operator>> rb50 = {proje, ex_5, t25};
  list<shared_ptr<Operator>> rb51 = {proje, ex_5, t26};
  list<shared_ptr<Operator>> rb52 = {proje, ex_5, t27};
  list<shared_ptr<Operator>> rb53 = {proje, ex_5, t28};
  list<shared_ptr<Operator>> rb54 = {proje, ex_6, t20};
  list<shared_ptr<Operator>> rb55 = {proje, ex_6, t21};
  list<shared_ptr<Operator>> rb56 = {proje, ex_6, t22};
  list<shared_ptr<Operator>> rb57 = {proje, ex_6, t23};
  list<shared_ptr<Operator>> rb58 = {proje, ex_6, t24};
  list<shared_ptr<Operator>> rb59 = {proje, ex_6, t25};
  list<shared_ptr<Operator>> rb60 = {proje, ex_6, t27};
  list<shared_ptr<Operator>> rb61 = {proje, ex_6, t28};
  list<shared_ptr<Operator>> rb62 = {proje, ex_7, t20};
  list<shared_ptr<Operator>> rb63 = {proje, ex_7, t21};
  list<shared_ptr<Operator>> rb64 = {proje, ex_7, t22};
  list<shared_ptr<Operator>> rb65 = {proje, ex_7, t23};
  list<shared_ptr<Operator>> rb66 = {proje, ex_7, t24};
  list<shared_ptr<Operator>> rb67 = {proje, ex_7, t25};
  list<shared_ptr<Operator>> rb68 = {proje, ex_7, t26};
  list<shared_ptr<Operator>> rb69 = {proje, ex_7, t27};
  list<shared_ptr<Operator>> rb70 = {proje, ex_7, t28};
  list<shared_ptr<Operator>> rb71 = {proje, ex_8, t20};
  list<shared_ptr<Operator>> rb72 = {proje, ex_8, t21};
  list<shared_ptr<Operator>> rb73 = {proje, ex_8, t22};
  list<shared_ptr<Operator>> rb74 = {proje, ex_8, t23};
  list<shared_ptr<Operator>> rb75 = {proje, ex_8, t24};
  list<shared_ptr<Operator>> rb76 = {proje, ex_8, t25};
  list<shared_ptr<Operator>> rb77 = {proje, ex_8, t26};
  list<shared_ptr<Operator>> rb78 = {proje, ex_8, t27};
  list<shared_ptr<Operator>> rb79 = {proje, ex_8, t28};
  auto dra0 = make_shared<Diagram>(ra0, 1, "");
  auto dra1 = make_shared<Diagram>(ra1, 1, "");
  auto dra2 = make_shared<Diagram>(ra2, 1, "");
  auto dra3 = make_shared<Diagram>(ra3, 1, "");
  auto dra4 = make_shared<Diagram>(ra4, 1, "");
  auto dra5 = make_shared<Diagram>(ra5, 1, "");
  auto dra6 = make_shared<Diagram>(ra6, 1, "");
  auto dra7 = make_shared<Diagram>(ra7, 1, "");
  auto dra8 = make_shared<Diagram>(ra8, 1, "");
  auto dra9 = make_shared<Diagram>(ra9, 1, "");
  auto dra10 = make_shared<Diagram>(ra10, 1, "");
  auto dra11 = make_shared<Diagram>(ra11, 1, "");
  auto dra12 = make_shared<Diagram>(ra12, 1, "");
  auto dra13 = make_shared<Diagram>(ra13, 1, "");
  auto dra14 = make_shared<Diagram>(ra14, 1, "");
  auto dra15 = make_shared<Diagram>(ra15, 1, "");
  auto dra16 = make_shared<Diagram>(ra16, 1, "");
  auto dra17 = make_shared<Diagram>(ra17, 1, "");
  auto dra18 = make_shared<Diagram>(ra18, 1, "");
  auto dra19 = make_shared<Diagram>(ra19, 1, "");
  auto dra20 = make_shared<Diagram>(ra20, 1, "");
  auto dra21 = make_shared<Diagram>(ra21, 1, "");
  auto dra22 = make_shared<Diagram>(ra22, 1, "");
  auto dra23 = make_shared<Diagram>(ra23, 1, "");
  auto dra24 = make_shared<Diagram>(ra24, 1, "");
  auto dra25 = make_shared<Diagram>(ra25, 1, "");
  auto dra26 = make_shared<Diagram>(ra26, 1, "");
  auto dra27 = make_shared<Diagram>(ra27, 1, "");
  auto dra28 = make_shared<Diagram>(ra28, 1, "");
  auto dra29 = make_shared<Diagram>(ra29, 1, "");
  auto dra30 = make_shared<Diagram>(ra30, 1, "");
  auto dra31 = make_shared<Diagram>(ra31, 1, "");
  auto dra32 = make_shared<Diagram>(ra32, 1, "");
  auto dra33 = make_shared<Diagram>(ra33, 1, "");
  auto dra34 = make_shared<Diagram>(ra34, 1, "");
  auto dra35 = make_shared<Diagram>(ra35, 1, "");
  auto dra36 = make_shared<Diagram>(ra36, 1, "");
  auto dra37 = make_shared<Diagram>(ra37, 1, "");
  auto dra38 = make_shared<Diagram>(ra38, 1, "");
  auto dra39 = make_shared<Diagram>(ra39, 1, "");
  auto dra40 = make_shared<Diagram>(ra40, 1, "");
  auto dra41 = make_shared<Diagram>(ra41, 1, "");
  auto dra42 = make_shared<Diagram>(ra42, 1, "");
  auto dra43 = make_shared<Diagram>(ra43, 1, "");
  auto dra44 = make_shared<Diagram>(ra44, 1, "");
  auto dra45 = make_shared<Diagram>(ra45, 1, "");
  auto dra46 = make_shared<Diagram>(ra46, 1, "");
  auto dra47 = make_shared<Diagram>(ra47, 1, "");
  auto dra48 = make_shared<Diagram>(ra48, 1, "");
  auto dra49 = make_shared<Diagram>(ra49, 1, "");
  auto dra50 = make_shared<Diagram>(ra50, 1, "");
  auto dra51 = make_shared<Diagram>(ra51, 1, "");
  auto dra52 = make_shared<Diagram>(ra52, 1, "");
  auto dra53 = make_shared<Diagram>(ra53, 1, "");
  auto dra54 = make_shared<Diagram>(ra54, 1, "");
  auto dra55 = make_shared<Diagram>(ra55, 1, "");
  auto dra56 = make_shared<Diagram>(ra56, 1, "");
  auto dra57 = make_shared<Diagram>(ra57, 1, "");
  auto dra58 = make_shared<Diagram>(ra58, 1, "");
  auto dra59 = make_shared<Diagram>(ra59, 1, "");
  auto dra60 = make_shared<Diagram>(ra60, 1, "");
  auto dra61 = make_shared<Diagram>(ra61, 1, "");
  auto dra62 = make_shared<Diagram>(ra62, 1, "");
  auto dra63 = make_shared<Diagram>(ra63, 1, "");
  auto dra64 = make_shared<Diagram>(ra64, 1, "");
  auto dra65 = make_shared<Diagram>(ra65, 1, "");
  auto dra66 = make_shared<Diagram>(ra66, 1, "");
  auto dra67 = make_shared<Diagram>(ra67, 1, "");
  auto dra68 = make_shared<Diagram>(ra68, 1, "");
  auto dra69 = make_shared<Diagram>(ra69, 1, "");
  auto dra70 = make_shared<Diagram>(ra70, 1, "");
  auto dra71 = make_shared<Diagram>(ra71, 1, "");
  auto dra72 = make_shared<Diagram>(ra72, 1, "");
  auto dra73 = make_shared<Diagram>(ra73, 1, "");
  auto dra74 = make_shared<Diagram>(ra74, 1, "");
  auto dra75 = make_shared<Diagram>(ra75, 1, "");
  auto dra76 = make_shared<Diagram>(ra76, 1, "");
  auto dra77 = make_shared<Diagram>(ra77, 1, "");
  auto dra78 = make_shared<Diagram>(ra78, 1, "");
  auto dra79 = make_shared<Diagram>(ra79, 1, "");
  auto drb0 = make_shared<Diagram>(rb0, -1, "e0");
  auto drb1 = make_shared<Diagram>(rb1, -1, "e0");
  auto drb2 = make_shared<Diagram>(rb2, -1, "e0");
  auto drb3 = make_shared<Diagram>(rb3, -1, "e0");
  auto drb4 = make_shared<Diagram>(rb4, -1, "e0");
  auto drb5 = make_shared<Diagram>(rb5, -1, "e0");
  auto drb6 = make_shared<Diagram>(rb6, -1, "e0");
  auto drb7 = make_shared<Diagram>(rb7, -1, "e0");
  auto drb8 = make_shared<Diagram>(rb8, -1, "e0");
  auto drb9 = make_shared<Diagram>(rb9, -1, "e0");
  auto drb10 = make_shared<Diagram>(rb10, -1, "e0");
  auto drb11 = make_shared<Diagram>(rb11, -1, "e0");
  auto drb12 = make_shared<Diagram>(rb12, -1, "e0");
  auto drb13 = make_shared<Diagram>(rb13, -1, "e0");
  auto drb14 = make_shared<Diagram>(rb14, -1, "e0");
  auto drb15 = make_shared<Diagram>(rb15, -1, "e0");
  auto drb16 = make_shared<Diagram>(rb16, -1, "e0");
  auto drb17 = make_shared<Diagram>(rb17, -1, "e0");
  auto drb18 = make_shared<Diagram>(rb18, -1, "e0");
  auto drb19 = make_shared<Diagram>(rb19, -1, "e0");
  auto drb20 = make_shared<Diagram>(rb20, -1, "e0");
  auto drb21 = make_shared<Diagram>(rb21, -1, "e0");
  auto drb22 = make_shared<Diagram>(rb22, -1, "e0");
  auto drb23 = make_shared<Diagram>(rb23, -1, "e0");
  auto drb24 = make_shared<Diagram>(rb24, -1, "e0");
  auto drb25 = make_shared<Diagram>(rb25, -1, "e0");
  auto drb26 = make_shared<Diagram>(rb26, -1, "e0");
  auto drb27 = make_shared<Diagram>(rb27, -1, "e0");
  auto drb28 = make_shared<Diagram>(rb28, -1, "e0");
  auto drb29 = make_shared<Diagram>(rb29, -1, "e0");
  auto drb30 = make_shared<Diagram>(rb30, -1, "e0");
  auto drb31 = make_shared<Diagram>(rb31, -1, "e0");
  auto drb32 = make_shared<Diagram>(rb32, -1, "e0");
  auto drb33 = make_shared<Diagram>(rb33, -1, "e0");
  auto drb34 = make_shared<Diagram>(rb34, -1, "e0");
  auto drb35 = make_shared<Diagram>(rb35, -1, "e0");
  auto drb36 = make_shared<Diagram>(rb36, -1, "e0");
  auto drb37 = make_shared<Diagram>(rb37, -1, "e0");
  auto drb38 = make_shared<Diagram>(rb38, -1, "e0");
  auto drb39 = make_shared<Diagram>(rb39, -1, "e0");
  auto drb40 = make_shared<Diagram>(rb40, -1, "e0");
  auto drb41 = make_shared<Diagram>(rb41, -1, "e0");
  auto drb42 = make_shared<Diagram>(rb42, -1, "e0");
  auto drb43 = make_shared<Diagram>(rb43, -1, "e0");
  auto drb44 = make_shared<Diagram>(rb44, -1, "e0");
  auto drb45 = make_shared<Diagram>(rb45, -1, "e0");
  auto drb46 = make_shared<Diagram>(rb46, -1, "e0");
  auto drb47 = make_shared<Diagram>(rb47, -1, "e0");
  auto drb48 = make_shared<Diagram>(rb48, -1, "e0");
  auto drb49 = make_shared<Diagram>(rb49, -1, "e0");
  auto drb50 = make_shared<Diagram>(rb50, -1, "e0");
  auto drb51 = make_shared<Diagram>(rb51, -1, "e0");
  auto drb52 = make_shared<Diagram>(rb52, -1, "e0");
  auto drb53 = make_shared<Diagram>(rb53, -1, "e0");
  auto drb54 = make_shared<Diagram>(rb54, -1, "e0");
  auto drb55 = make_shared<Diagram>(rb55, -1, "e0");
  auto drb56 = make_shared<Diagram>(rb56, -1, "e0");
  auto drb57 = make_shared<Diagram>(rb57, -1, "e0");
  auto drb58 = make_shared<Diagram>(rb58, -1, "e0");
  auto drb59 = make_shared<Diagram>(rb59, -1, "e0");
  auto drb60 = make_shared<Diagram>(rb60, -1, "e0");
  auto drb61 = make_shared<Diagram>(rb61, -1, "e0");
  auto drb62 = make_shared<Diagram>(rb62, -1, "e0");
  auto drb63 = make_shared<Diagram>(rb63, -1, "e0");
  auto drb64 = make_shared<Diagram>(rb64, -1, "e0");
  auto drb65 = make_shared<Diagram>(rb65, -1, "e0");
  auto drb66 = make_shared<Diagram>(rb66, -1, "e0");
  auto drb67 = make_shared<Diagram>(rb67, -1, "e0");
  auto drb68 = make_shared<Diagram>(rb68, -1, "e0");
  auto drb69 = make_shared<Diagram>(rb69, -1, "e0");
  auto drb70 = make_shared<Diagram>(rb70, -1, "e0");
  auto drb71 = make_shared<Diagram>(rb71, -1, "e0");
  auto drb72 = make_shared<Diagram>(rb72, -1, "e0");
  auto drb73 = make_shared<Diagram>(rb73, -1, "e0");
  auto drb74 = make_shared<Diagram>(rb74, -1, "e0");
  auto drb75 = make_shared<Diagram>(rb75, -1, "e0");
  auto drb76 = make_shared<Diagram>(rb76, -1, "e0");
  auto drb77 = make_shared<Diagram>(rb77, -1, "e0");
  auto drb78 = make_shared<Diagram>(rb78, -1, "e0");
  auto drb79 = make_shared<Diagram>(rb79, -1, "e0");
  auto era0 = make_shared<Equation>(dra0, theory);
  auto era1 = make_shared<Equation>(dra1, theory);
  auto era2 = make_shared<Equation>(dra2, theory);
  auto era3 = make_shared<Equation>(dra3, theory);
  auto era4 = make_shared<Equation>(dra4, theory);
  auto era5 = make_shared<Equation>(dra5, theory);
  auto era6 = make_shared<Equation>(dra6, theory);
  auto era7 = make_shared<Equation>(dra7, theory);
  auto era8 = make_shared<Equation>(dra8, theory);
  auto era9 = make_shared<Equation>(dra9, theory);
  auto era10 = make_shared<Equation>(dra10, theory);
  auto era11 = make_shared<Equation>(dra11, theory);
  auto era12 = make_shared<Equation>(dra12, theory);
  auto era13 = make_shared<Equation>(dra13, theory);
  auto era14 = make_shared<Equation>(dra14, theory);
  auto era15 = make_shared<Equation>(dra15, theory);
  auto era16 = make_shared<Equation>(dra16, theory);
  auto era17 = make_shared<Equation>(dra17, theory);
  auto era18 = make_shared<Equation>(dra18, theory);
  auto era19 = make_shared<Equation>(dra19, theory);
  auto era20 = make_shared<Equation>(dra20, theory);
  auto era21 = make_shared<Equation>(dra21, theory);
  auto era22 = make_shared<Equation>(dra22, theory);
  auto era23 = make_shared<Equation>(dra23, theory);
  auto era24 = make_shared<Equation>(dra24, theory);
  auto era25 = make_shared<Equation>(dra25, theory);
  auto era26 = make_shared<Equation>(dra26, theory);
  auto era27 = make_shared<Equation>(dra27, theory);
  auto era28 = make_shared<Equation>(dra28, theory);
  auto era29 = make_shared<Equation>(dra29, theory);
  auto era30 = make_shared<Equation>(dra30, theory);
  auto era31 = make_shared<Equation>(dra31, theory);
  auto era32 = make_shared<Equation>(dra32, theory);
  auto era33 = make_shared<Equation>(dra33, theory);
  auto era34 = make_shared<Equation>(dra34, theory);
  auto era35 = make_shared<Equation>(dra35, theory);
  auto era36 = make_shared<Equation>(dra36, theory);
  auto era37 = make_shared<Equation>(dra37, theory);
  auto era38 = make_shared<Equation>(dra38, theory);
  auto era39 = make_shared<Equation>(dra39, theory);
  auto era40 = make_shared<Equation>(dra40, theory);
  auto era41 = make_shared<Equation>(dra41, theory);
  auto era42 = make_shared<Equation>(dra42, theory);
  auto era43 = make_shared<Equation>(dra43, theory);
  auto era44 = make_shared<Equation>(dra44, theory);
  auto era45 = make_shared<Equation>(dra45, theory);
  auto era46 = make_shared<Equation>(dra46, theory);
  auto era47 = make_shared<Equation>(dra47, theory);
  auto era48 = make_shared<Equation>(dra48, theory);
  auto era49 = make_shared<Equation>(dra49, theory);
  auto era50 = make_shared<Equation>(dra50, theory);
  auto era51 = make_shared<Equation>(dra51, theory);
  auto era52 = make_shared<Equation>(dra52, theory);
  auto era53 = make_shared<Equation>(dra53, theory);
  auto era54 = make_shared<Equation>(dra54, theory);
  auto era55 = make_shared<Equation>(dra55, theory);
  auto era56 = make_shared<Equation>(dra56, theory);
  auto era57 = make_shared<Equation>(dra57, theory);
  auto era58 = make_shared<Equation>(dra58, theory);
  auto era59 = make_shared<Equation>(dra59, theory);
  auto era60 = make_shared<Equation>(dra60, theory);
  auto era61 = make_shared<Equation>(dra61, theory);
  auto era62 = make_shared<Equation>(dra62, theory);
  auto era63 = make_shared<Equation>(dra63, theory);
  auto era64 = make_shared<Equation>(dra64, theory);
  auto era65 = make_shared<Equation>(dra65, theory);
  auto era66 = make_shared<Equation>(dra66, theory);
  auto era67 = make_shared<Equation>(dra67, theory);
  auto era68 = make_shared<Equation>(dra68, theory);
  auto era69 = make_shared<Equation>(dra69, theory);
  auto era70 = make_shared<Equation>(dra70, theory);
  auto era71 = make_shared<Equation>(dra71, theory);
  auto era72 = make_shared<Equation>(dra72, theory);
  auto era73 = make_shared<Equation>(dra73, theory);
  auto era74 = make_shared<Equation>(dra74, theory);
  auto era75 = make_shared<Equation>(dra75, theory);
  auto era76 = make_shared<Equation>(dra76, theory);
  auto era77 = make_shared<Equation>(dra77, theory);
  auto era78 = make_shared<Equation>(dra78, theory);
  auto era79 = make_shared<Equation>(dra79, theory);
  auto erb0 = make_shared<Equation>(drb0, theory);
  auto erb1 = make_shared<Equation>(drb1, theory);
  auto erb2 = make_shared<Equation>(drb2, theory);
  auto erb3 = make_shared<Equation>(drb3, theory);
  auto erb4 = make_shared<Equation>(drb4, theory);
  auto erb5 = make_shared<Equation>(drb5, theory);
  auto erb6 = make_shared<Equation>(drb6, theory);
  auto erb7 = make_shared<Equation>(drb7, theory);
  auto erb8 = make_shared<Equation>(drb8, theory);
  auto erb9 = make_shared<Equation>(drb9, theory);
  auto erb10 = make_shared<Equation>(drb10, theory);
  auto erb11 = make_shared<Equation>(drb11, theory);
  auto erb12 = make_shared<Equation>(drb12, theory);
  auto erb13 = make_shared<Equation>(drb13, theory);
  auto erb14 = make_shared<Equation>(drb14, theory);
  auto erb15 = make_shared<Equation>(drb15, theory);
  auto erb16 = make_shared<Equation>(drb16, theory);
  auto erb17 = make_shared<Equation>(drb17, theory);
  auto erb18 = make_shared<Equation>(drb18, theory);
  auto erb19 = make_shared<Equation>(drb19, theory);
  auto erb20 = make_shared<Equation>(drb20, theory);
  auto erb21 = make_shared<Equation>(drb21, theory);
  auto erb22 = make_shared<Equation>(drb22, theory);
  auto erb23 = make_shared<Equation>(drb23, theory);
  auto erb24 = make_shared<Equation>(drb24, theory);
  auto erb25 = make_shared<Equation>(drb25, theory);
  auto erb26 = make_shared<Equation>(drb26, theory);
  auto erb27 = make_shared<Equation>(drb27, theory);
  auto erb28 = make_shared<Equation>(drb28, theory);
  auto erb29 = make_shared<Equation>(drb29, theory);
  auto erb30 = make_shared<Equation>(drb30, theory);
  auto erb31 = make_shared<Equation>(drb31, theory);
  auto erb32 = make_shared<Equation>(drb32, theory);
  auto erb33 = make_shared<Equation>(drb33, theory);
  auto erb34 = make_shared<Equation>(drb34, theory);
  auto erb35 = make_shared<Equation>(drb35, theory);
  auto erb36 = make_shared<Equation>(drb36, theory);
  auto erb37 = make_shared<Equation>(drb37, theory);
  auto erb38 = make_shared<Equation>(drb38, theory);
  auto erb39 = make_shared<Equation>(drb39, theory);
  auto erb40 = make_shared<Equation>(drb40, theory);
  auto erb41 = make_shared<Equation>(drb41, theory);
  auto erb42 = make_shared<Equation>(drb42, theory);
  auto erb43 = make_shared<Equation>(drb43, theory);
  auto erb44 = make_shared<Equation>(drb44, theory);
  auto erb45 = make_shared<Equation>(drb45, theory);
  auto erb46 = make_shared<Equation>(drb46, theory);
  auto erb47 = make_shared<Equation>(drb47, theory);
  auto erb48 = make_shared<Equation>(drb48, theory);
  auto erb49 = make_shared<Equation>(drb49, theory);
  auto erb50 = make_shared<Equation>(drb50, theory);
  auto erb51 = make_shared<Equation>(drb51, theory);
  auto erb52 = make_shared<Equation>(drb52, theory);
  auto erb53 = make_shared<Equation>(drb53, theory);
  auto erb54 = make_shared<Equation>(drb54, theory);
  auto erb55 = make_shared<Equation>(drb55, theory);
  auto erb56 = make_shared<Equation>(drb56, theory);
  auto erb57 = make_shared<Equation>(drb57, theory);
  auto erb58 = make_shared<Equation>(drb58, theory);
  auto erb59 = make_shared<Equation>(drb59, theory);
  auto erb60 = make_shared<Equation>(drb60, theory);
  auto erb61 = make_shared<Equation>(drb61, theory);
  auto erb62 = make_shared<Equation>(drb62, theory);
  auto erb63 = make_shared<Equation>(drb63, theory);
  auto erb64 = make_shared<Equation>(drb64, theory);
  auto erb65 = make_shared<Equation>(drb65, theory);
  auto erb66 = make_shared<Equation>(drb66, theory);
  auto erb67 = make_shared<Equation>(drb67, theory);
  auto erb68 = make_shared<Equation>(drb68, theory);
  auto erb69 = make_shared<Equation>(drb69, theory);
  auto erb70 = make_shared<Equation>(drb70, theory);
  auto erb71 = make_shared<Equation>(drb71, theory);
  auto erb72 = make_shared<Equation>(drb72, theory);
  auto erb73 = make_shared<Equation>(drb73, theory);
  auto erb74 = make_shared<Equation>(drb74, theory);
  auto erb75 = make_shared<Equation>(drb75, theory);
  auto erb76 = make_shared<Equation>(drb76, theory);
  auto erb77 = make_shared<Equation>(drb77, theory);
  auto erb78 = make_shared<Equation>(drb78, theory);
  auto erb79 = make_shared<Equation>(drb79, theory);
  era0->merge(era1);
  era0->merge(era2);
  era0->merge(era3);
  era0->merge(era4);
  era0->merge(era5);
  era0->merge(era6);
  era0->merge(era7);
  era0->merge(era8);
  era0->merge(era9);
  era0->merge(era10);
  era0->merge(era11);
  era0->merge(era12);
  era0->merge(era13);
  era0->merge(era14);
  era0->merge(era15);
  era0->merge(era16);
  era0->merge(era17);
  era0->merge(era18);
  era0->merge(era19);
  era0->merge(era20);
  era0->merge(era21);
  era0->merge(era22);
  era0->merge(era23);
  era0->merge(era24);
  era0->merge(era25);
  era0->merge(era26);
  era0->merge(era27);
  era0->merge(era28);
  era0->merge(era29);
  era0->merge(era30);
  era0->merge(era31);
  era0->merge(era32);
  era0->merge(era33);
  era0->merge(era34);
  era0->merge(era35);
  era0->merge(era36);
  era0->merge(era37);
  era0->merge(era38);
  era0->merge(era39);
  era0->merge(era40);
  era0->merge(era41);
  era0->merge(era42);
  era0->merge(era43);
  era0->merge(era44);
  era0->merge(era45);
  era0->merge(era46);
  era0->merge(era47);
  era0->merge(era48);
  era0->merge(era49);
  era0->merge(era50);
  era0->merge(era51);
  era0->merge(era52);
  era0->merge(era53);
  era0->merge(era54);
  era0->merge(era55);
  era0->merge(era56);
  era0->merge(era57);
  era0->merge(era58);
  era0->merge(era59);
  era0->merge(era60);
  era0->merge(era61);
  era0->merge(era62);
  era0->merge(era63);
  era0->merge(era64);
  era0->merge(era65);
  era0->merge(era66);
  era0->merge(era67);
  era0->merge(era68);
  era0->merge(era69);
  era0->merge(era70);
  era0->merge(era71);
  era0->merge(era72);
  era0->merge(era73);
  era0->merge(era74);
  era0->merge(era75);
  era0->merge(era76);
  era0->merge(era77);
  era0->merge(era78);
  era0->merge(era79);
  era0->merge(erb0);
  era0->merge(erb1);
  era0->merge(erb2);
  era0->merge(erb3);
  era0->merge(erb4);
  era0->merge(erb5);
  era0->merge(erb6);
  era0->merge(erb7);
  era0->merge(erb8);
  era0->merge(erb9);
  era0->merge(erb10);
  era0->merge(erb11);
  era0->merge(erb12);
  era0->merge(erb13);
  era0->merge(erb14);
  era0->merge(erb15);
  era0->merge(erb16);
  era0->merge(erb17);
  era0->merge(erb18);
  era0->merge(erb19);
  era0->merge(erb20);
  era0->merge(erb21);
  era0->merge(erb22);
  era0->merge(erb23);
  era0->merge(erb24);
  era0->merge(erb25);
  era0->merge(erb26);
  era0->merge(erb27);
  era0->merge(erb28);
  era0->merge(erb29);
  era0->merge(erb30);
  era0->merge(erb31);
  era0->merge(erb32);
  era0->merge(erb33);
  era0->merge(erb34);
  era0->merge(erb35);
  era0->merge(erb36);
  era0->merge(erb37);
  era0->merge(erb38);
  era0->merge(erb39);
  era0->merge(erb40);
  era0->merge(erb41);
  era0->merge(erb42);
  era0->merge(erb43);
  era0->merge(erb44);
  era0->merge(erb45);
  era0->merge(erb46);
  era0->merge(erb47);
  era0->merge(erb48);
  era0->merge(erb49);
  era0->merge(erb50);
  era0->merge(erb51);
  era0->merge(erb52);
  era0->merge(erb53);
  era0->merge(erb54);
  era0->merge(erb55);
  era0->merge(erb56);
  era0->merge(erb57);
  era0->merge(erb58);
  era0->merge(erb59);
  era0->merge(erb60);
  era0->merge(erb61);
  era0->merge(erb62);
  era0->merge(erb63);
  era0->merge(erb64);
  era0->merge(erb65);
  era0->merge(erb66);
  era0->merge(erb67);
  era0->merge(erb68);
  era0->merge(erb69);
  era0->merge(erb70);
  era0->merge(erb71);
  era0->merge(erb72);
  era0->merge(erb73);
  era0->merge(erb74);
  era0->merge(erb75);
  era0->merge(erb76);
  era0->merge(erb77);
  era0->merge(erb78);
  era0->merge(erb79);
  era0->duplicates();
  era0->active();
  auto tra = make_shared<Residual>(era0, "residual");

  list<shared_ptr<Operator>> ec0 = {proje, ex_0, v2};
  list<shared_ptr<Operator>> ec1 = {proje, ex_1, v2};
  list<shared_ptr<Operator>> ec2 = {proje, ex_2, v2};
  list<shared_ptr<Operator>> ec3 = {proje, ex_3, v2};
  list<shared_ptr<Operator>> ec4 = {proje, ex_4, v2};
  list<shared_ptr<Operator>> ec5 = {proje, ex_5, v2};
  list<shared_ptr<Operator>> ec6 = {proje, ex_6, v2};
  list<shared_ptr<Operator>> ec7 = {proje, ex_7, v2};
  list<shared_ptr<Operator>> ec8 = {proje, ex_8, v2};
  list<shared_ptr<Operator>> ed0 = {proje, ex_0, h1};
  list<shared_ptr<Operator>> ed1 = {proje, ex_1, h1};
  list<shared_ptr<Operator>> ed2 = {proje, ex_2, h1};
  list<shared_ptr<Operator>> ed3 = {proje, ex_3, h1};
  list<shared_ptr<Operator>> ed4 = {proje, ex_4, h1};
  list<shared_ptr<Operator>> ed5 = {proje, ex_5, h1};
  list<shared_ptr<Operator>> ed6 = {proje, ex_6, h1};
  list<shared_ptr<Operator>> ed7 = {proje, ex_7, h1};
  list<shared_ptr<Operator>> ed8 = {proje, ex_8, h1};
  auto dec0 = make_shared<Diagram>(ec0, 0.5, "");
  auto dec1 = make_shared<Diagram>(ec1, 0.5, "");
  auto dec2 = make_shared<Diagram>(ec2, 0.5, "");
  auto dec3 = make_shared<Diagram>(ec3, 0.5, "");
  auto dec4 = make_shared<Diagram>(ec4, 0.5, "");
  auto dec5 = make_shared<Diagram>(ec5, 0.5, "");
  auto dec6 = make_shared<Diagram>(ec6, 0.5, "");
  auto dec7 = make_shared<Diagram>(ec7, 0.5, "");
  auto dec8 = make_shared<Diagram>(ec8, 0.5, "");
  auto ded0 = make_shared<Diagram>(ed0, 1, "");
  auto ded1 = make_shared<Diagram>(ed1, 1, "");
  auto ded2 = make_shared<Diagram>(ed2, 1, "");
  auto ded3 = make_shared<Diagram>(ed3, 1, "");
  auto ded4 = make_shared<Diagram>(ed4, 1, "");
  auto ded5 = make_shared<Diagram>(ed5, 1, "");
  auto ded6 = make_shared<Diagram>(ed6, 1, "");
  auto ded7 = make_shared<Diagram>(ed7, 1, "");
  auto ded8 = make_shared<Diagram>(ed8, 1, "");
  auto eec0 = make_shared<Equation>(dec0, theory);
  auto eec1 = make_shared<Equation>(dec1, theory);
  auto eec2 = make_shared<Equation>(dec2, theory);
  auto eec3 = make_shared<Equation>(dec3, theory);
  auto eec4 = make_shared<Equation>(dec4, theory);
  auto eec5 = make_shared<Equation>(dec5, theory);
  auto eec6 = make_shared<Equation>(dec6, theory);
  auto eec7 = make_shared<Equation>(dec7, theory);
  auto eec8 = make_shared<Equation>(dec8, theory);
  auto eed0 = make_shared<Equation>(ded0, theory);
  auto eed1 = make_shared<Equation>(ded1, theory);
  auto eed2 = make_shared<Equation>(ded2, theory);
  auto eed3 = make_shared<Equation>(ded3, theory);
  auto eed4 = make_shared<Equation>(ded4, theory);
  auto eed5 = make_shared<Equation>(ded5, theory);
  auto eed6 = make_shared<Equation>(ded6, theory);
  auto eed7 = make_shared<Equation>(ded7, theory);
  auto eed8 = make_shared<Equation>(ded8, theory);
  eec0->merge(eec1);
  eec0->merge(eec2);
  eec0->merge(eec3);
  eec0->merge(eec4);
  eec0->merge(eec5);
  eec0->merge(eec6);
  eec0->merge(eec7);
  eec0->merge(eec8);
  eec0->merge(eed0);
  eec0->merge(eed1);
  eec0->merge(eed2);
  eec0->merge(eed3);
  eec0->merge(eed4);
  eec0->merge(eed5);
  eec0->merge(eed6);
  eec0->merge(eed7);
  eec0->merge(eed8);
  eec0->duplicates();
  eec0->active();
  auto tec = make_shared<Residual>(eec0, "source");

  list<shared_ptr<Operator>> ca0 = {proje, ex_0, t20};
  list<shared_ptr<Operator>> ca1 = {proje, ex_0, t21};
  list<shared_ptr<Operator>> ca2 = {proje, ex_0, t22};
  list<shared_ptr<Operator>> ca3 = {proje, ex_0, t23};
  list<shared_ptr<Operator>> ca4 = {proje, ex_0, t24};
  list<shared_ptr<Operator>> ca5 = {proje, ex_0, t25};
  list<shared_ptr<Operator>> ca6 = {proje, ex_0, t26};
  list<shared_ptr<Operator>> ca7 = {proje, ex_0, t27};
  list<shared_ptr<Operator>> ca8 = {proje, ex_0, t28};
  list<shared_ptr<Operator>> ca9 = {proje, ex_1, t20};
  list<shared_ptr<Operator>> ca10 = {proje, ex_1, t21};
  list<shared_ptr<Operator>> ca11 = {proje, ex_1, t22};
  list<shared_ptr<Operator>> ca12 = {proje, ex_1, t23};
  list<shared_ptr<Operator>> ca13 = {proje, ex_1, t24};
  list<shared_ptr<Operator>> ca14 = {proje, ex_1, t25};
  list<shared_ptr<Operator>> ca15 = {proje, ex_1, t26};
  list<shared_ptr<Operator>> ca16 = {proje, ex_1, t27};
  list<shared_ptr<Operator>> ca17 = {proje, ex_1, t28};
  list<shared_ptr<Operator>> ca18 = {proje, ex_2, t20};
  list<shared_ptr<Operator>> ca19 = {proje, ex_2, t21};
  list<shared_ptr<Operator>> ca20 = {proje, ex_2, t22};
  list<shared_ptr<Operator>> ca21 = {proje, ex_2, t23};
  list<shared_ptr<Operator>> ca22 = {proje, ex_2, t24};
  list<shared_ptr<Operator>> ca23 = {proje, ex_2, t25};
  list<shared_ptr<Operator>> ca24 = {proje, ex_2, t26};
  list<shared_ptr<Operator>> ca25 = {proje, ex_2, t27};
  list<shared_ptr<Operator>> ca26 = {proje, ex_2, t28};
  list<shared_ptr<Operator>> ca27 = {proje, ex_3, t20};
  list<shared_ptr<Operator>> ca28 = {proje, ex_3, t21};
  list<shared_ptr<Operator>> ca29 = {proje, ex_3, t22};
  list<shared_ptr<Operator>> ca30 = {proje, ex_3, t23};
  list<shared_ptr<Operator>> ca31 = {proje, ex_3, t24};
  list<shared_ptr<Operator>> ca32 = {proje, ex_3, t25};
  list<shared_ptr<Operator>> ca33 = {proje, ex_3, t26};
  list<shared_ptr<Operator>> ca34 = {proje, ex_3, t27};
  list<shared_ptr<Operator>> ca35 = {proje, ex_3, t28};
  list<shared_ptr<Operator>> ca36 = {proje, ex_4, t20};
  list<shared_ptr<Operator>> ca37 = {proje, ex_4, t21};
  list<shared_ptr<Operator>> ca38 = {proje, ex_4, t22};
  list<shared_ptr<Operator>> ca39 = {proje, ex_4, t23};
  list<shared_ptr<Operator>> ca40 = {proje, ex_4, t24};
  list<shared_ptr<Operator>> ca41 = {proje, ex_4, t25};
  list<shared_ptr<Operator>> ca42 = {proje, ex_4, t26};
  list<shared_ptr<Operator>> ca43 = {proje, ex_4, t27};
  list<shared_ptr<Operator>> ca44 = {proje, ex_4, t28};
  list<shared_ptr<Operator>> ca45 = {proje, ex_5, t20};
  list<shared_ptr<Operator>> ca46 = {proje, ex_5, t21};
  list<shared_ptr<Operator>> ca47 = {proje, ex_5, t22};
  list<shared_ptr<Operator>> ca48 = {proje, ex_5, t23};
  list<shared_ptr<Operator>> ca49 = {proje, ex_5, t24};
  list<shared_ptr<Operator>> ca50 = {proje, ex_5, t25};
  list<shared_ptr<Operator>> ca51 = {proje, ex_5, t26};
  list<shared_ptr<Operator>> ca52 = {proje, ex_5, t27};
  list<shared_ptr<Operator>> ca53 = {proje, ex_5, t28};
  list<shared_ptr<Operator>> ca54 = {proje, ex_6, t20};
  list<shared_ptr<Operator>> ca55 = {proje, ex_6, t21};
  list<shared_ptr<Operator>> ca56 = {proje, ex_6, t22};
  list<shared_ptr<Operator>> ca57 = {proje, ex_6, t23};
  list<shared_ptr<Operator>> ca58 = {proje, ex_6, t24};
  list<shared_ptr<Operator>> ca59 = {proje, ex_6, t25};
  list<shared_ptr<Operator>> ca60 = {proje, ex_6, t26};
  list<shared_ptr<Operator>> ca61 = {proje, ex_6, t27};
  list<shared_ptr<Operator>> ca62 = {proje, ex_6, t28};
  list<shared_ptr<Operator>> ca63 = {proje, ex_7, t20};
  list<shared_ptr<Operator>> ca64 = {proje, ex_7, t21};
  list<shared_ptr<Operator>> ca65 = {proje, ex_7, t22};
  list<shared_ptr<Operator>> ca66 = {proje, ex_7, t23};
  list<shared_ptr<Operator>> ca67 = {proje, ex_7, t24};
  list<shared_ptr<Operator>> ca68 = {proje, ex_7, t25};
  list<shared_ptr<Operator>> ca69 = {proje, ex_7, t26};
  list<shared_ptr<Operator>> ca70 = {proje, ex_7, t27};
  list<shared_ptr<Operator>> ca71 = {proje, ex_7, t28};
  list<shared_ptr<Operator>> ca72 = {proje, ex_8, t20};
  list<shared_ptr<Operator>> ca73 = {proje, ex_8, t21};
  list<shared_ptr<Operator>> ca74 = {proje, ex_8, t22};
  list<shared_ptr<Operator>> ca75 = {proje, ex_8, t23};
  list<shared_ptr<Operator>> ca76 = {proje, ex_8, t24};
  list<shared_ptr<Operator>> ca77 = {proje, ex_8, t25};
  list<shared_ptr<Operator>> ca78 = {proje, ex_8, t26};
  list<shared_ptr<Operator>> ca79 = {proje, ex_8, t27};
  list<shared_ptr<Operator>> ca80 = {proje, ex_8, t28};
  auto dca0 = make_shared<Diagram>(ca0, 1, "");
  auto dca1 = make_shared<Diagram>(ca1, 1, "");
  auto dca2 = make_shared<Diagram>(ca2, 1, "");
  auto dca3 = make_shared<Diagram>(ca3, 1, "");
  auto dca4 = make_shared<Diagram>(ca4, 1, "");
  auto dca5 = make_shared<Diagram>(ca5, 1, "");
  auto dca6 = make_shared<Diagram>(ca6, 1, "");
  auto dca7 = make_shared<Diagram>(ca7, 1, "");
  auto dca8 = make_shared<Diagram>(ca8, 1, "");
  auto dca9 = make_shared<Diagram>(ca9, 1, "");
  auto dca10 = make_shared<Diagram>(ca10, 1, "");
  auto dca11 = make_shared<Diagram>(ca11, 1, "");
  auto dca12 = make_shared<Diagram>(ca12, 1, "");
  auto dca13 = make_shared<Diagram>(ca13, 1, "");
  auto dca14 = make_shared<Diagram>(ca14, 1, "");
  auto dca15 = make_shared<Diagram>(ca15, 1, "");
  auto dca16 = make_shared<Diagram>(ca16, 1, "");
  auto dca17 = make_shared<Diagram>(ca17, 1, "");
  auto dca18 = make_shared<Diagram>(ca18, 1, "");
  auto dca19 = make_shared<Diagram>(ca19, 1, "");
  auto dca20 = make_shared<Diagram>(ca20, 1, "");
  auto dca21 = make_shared<Diagram>(ca21, 1, "");
  auto dca22 = make_shared<Diagram>(ca22, 1, "");
  auto dca23 = make_shared<Diagram>(ca23, 1, "");
  auto dca24 = make_shared<Diagram>(ca24, 1, "");
  auto dca25 = make_shared<Diagram>(ca25, 1, "");
  auto dca26 = make_shared<Diagram>(ca26, 1, "");
  auto dca27 = make_shared<Diagram>(ca27, 1, "");
  auto dca28 = make_shared<Diagram>(ca28, 1, "");
  auto dca29 = make_shared<Diagram>(ca29, 1, "");
  auto dca30 = make_shared<Diagram>(ca30, 1, "");
  auto dca31 = make_shared<Diagram>(ca31, 1, "");
  auto dca32 = make_shared<Diagram>(ca32, 1, "");
  auto dca33 = make_shared<Diagram>(ca33, 1, "");
  auto dca34 = make_shared<Diagram>(ca34, 1, "");
  auto dca35 = make_shared<Diagram>(ca35, 1, "");
  auto dca36 = make_shared<Diagram>(ca36, 1, "");
  auto dca37 = make_shared<Diagram>(ca37, 1, "");
  auto dca38 = make_shared<Diagram>(ca38, 1, "");
  auto dca39 = make_shared<Diagram>(ca39, 1, "");
  auto dca40 = make_shared<Diagram>(ca40, 1, "");
  auto dca41 = make_shared<Diagram>(ca41, 1, "");
  auto dca42 = make_shared<Diagram>(ca42, 1, "");
  auto dca43 = make_shared<Diagram>(ca43, 1, "");
  auto dca44 = make_shared<Diagram>(ca44, 1, "");
  auto dca45 = make_shared<Diagram>(ca45, 1, "");
  auto dca46 = make_shared<Diagram>(ca46, 1, "");
  auto dca47 = make_shared<Diagram>(ca47, 1, "");
  auto dca48 = make_shared<Diagram>(ca48, 1, "");
  auto dca49 = make_shared<Diagram>(ca49, 1, "");
  auto dca50 = make_shared<Diagram>(ca50, 1, "");
  auto dca51 = make_shared<Diagram>(ca51, 1, "");
  auto dca52 = make_shared<Diagram>(ca52, 1, "");
  auto dca53 = make_shared<Diagram>(ca53, 1, "");
  auto dca54 = make_shared<Diagram>(ca54, 1, "");
  auto dca55 = make_shared<Diagram>(ca55, 1, "");
  auto dca56 = make_shared<Diagram>(ca56, 1, "");
  auto dca57 = make_shared<Diagram>(ca57, 1, "");
  auto dca58 = make_shared<Diagram>(ca58, 1, "");
  auto dca59 = make_shared<Diagram>(ca59, 1, "");
  auto dca60 = make_shared<Diagram>(ca60, 1, "");
  auto dca61 = make_shared<Diagram>(ca61, 1, "");
  auto dca62 = make_shared<Diagram>(ca62, 1, "");
  auto dca63 = make_shared<Diagram>(ca63, 1, "");
  auto dca64 = make_shared<Diagram>(ca64, 1, "");
  auto dca65 = make_shared<Diagram>(ca65, 1, "");
  auto dca66 = make_shared<Diagram>(ca66, 1, "");
  auto dca67 = make_shared<Diagram>(ca67, 1, "");
  auto dca68 = make_shared<Diagram>(ca68, 1, "");
  auto dca69 = make_shared<Diagram>(ca69, 1, "");
  auto dca70 = make_shared<Diagram>(ca70, 1, "");
  auto dca71 = make_shared<Diagram>(ca71, 1, "");
  auto dca72 = make_shared<Diagram>(ca72, 1, "");
  auto dca73 = make_shared<Diagram>(ca73, 1, "");
  auto dca74 = make_shared<Diagram>(ca74, 1, "");
  auto dca75 = make_shared<Diagram>(ca75, 1, "");
  auto dca76 = make_shared<Diagram>(ca76, 1, "");
  auto dca77 = make_shared<Diagram>(ca77, 1, "");
  auto dca78 = make_shared<Diagram>(ca78, 1, "");
  auto dca79 = make_shared<Diagram>(ca79, 1, "");
  auto dca80 = make_shared<Diagram>(ca80, 1, "");
  auto eca0 = make_shared<Equation>(dca0, theory);
  auto eca1 = make_shared<Equation>(dca1, theory);
  auto eca2 = make_shared<Equation>(dca2, theory);
  auto eca3 = make_shared<Equation>(dca3, theory);
  auto eca4 = make_shared<Equation>(dca4, theory);
  auto eca5 = make_shared<Equation>(dca5, theory);
  auto eca6 = make_shared<Equation>(dca6, theory);
  auto eca7 = make_shared<Equation>(dca7, theory);
  auto eca8 = make_shared<Equation>(dca8, theory);
  auto eca9 = make_shared<Equation>(dca9, theory);
  auto eca10 = make_shared<Equation>(dca10, theory);
  auto eca11 = make_shared<Equation>(dca11, theory);
  auto eca12 = make_shared<Equation>(dca12, theory);
  auto eca13 = make_shared<Equation>(dca13, theory);
  auto eca14 = make_shared<Equation>(dca14, theory);
  auto eca15 = make_shared<Equation>(dca15, theory);
  auto eca16 = make_shared<Equation>(dca16, theory);
  auto eca17 = make_shared<Equation>(dca17, theory);
  auto eca18 = make_shared<Equation>(dca18, theory);
  auto eca19 = make_shared<Equation>(dca19, theory);
  auto eca20 = make_shared<Equation>(dca20, theory);
  auto eca21 = make_shared<Equation>(dca21, theory);
  auto eca22 = make_shared<Equation>(dca22, theory);
  auto eca23 = make_shared<Equation>(dca23, theory);
  auto eca24 = make_shared<Equation>(dca24, theory);
  auto eca25 = make_shared<Equation>(dca25, theory);
  auto eca26 = make_shared<Equation>(dca26, theory);
  auto eca27 = make_shared<Equation>(dca27, theory);
  auto eca28 = make_shared<Equation>(dca28, theory);
  auto eca29 = make_shared<Equation>(dca29, theory);
  auto eca30 = make_shared<Equation>(dca30, theory);
  auto eca31 = make_shared<Equation>(dca31, theory);
  auto eca32 = make_shared<Equation>(dca32, theory);
  auto eca33 = make_shared<Equation>(dca33, theory);
  auto eca34 = make_shared<Equation>(dca34, theory);
  auto eca35 = make_shared<Equation>(dca35, theory);
  auto eca36 = make_shared<Equation>(dca36, theory);
  auto eca37 = make_shared<Equation>(dca37, theory);
  auto eca38 = make_shared<Equation>(dca38, theory);
  auto eca39 = make_shared<Equation>(dca39, theory);
  auto eca40 = make_shared<Equation>(dca40, theory);
  auto eca41 = make_shared<Equation>(dca41, theory);
  auto eca42 = make_shared<Equation>(dca42, theory);
  auto eca43 = make_shared<Equation>(dca43, theory);
  auto eca44 = make_shared<Equation>(dca44, theory);
  auto eca45 = make_shared<Equation>(dca45, theory);
  auto eca46 = make_shared<Equation>(dca46, theory);
  auto eca47 = make_shared<Equation>(dca47, theory);
  auto eca48 = make_shared<Equation>(dca48, theory);
  auto eca49 = make_shared<Equation>(dca49, theory);
  auto eca50 = make_shared<Equation>(dca50, theory);
  auto eca51 = make_shared<Equation>(dca51, theory);
  auto eca52 = make_shared<Equation>(dca52, theory);
  auto eca53 = make_shared<Equation>(dca53, theory);
  auto eca54 = make_shared<Equation>(dca54, theory);
  auto eca55 = make_shared<Equation>(dca55, theory);
  auto eca56 = make_shared<Equation>(dca56, theory);
  auto eca57 = make_shared<Equation>(dca57, theory);
  auto eca58 = make_shared<Equation>(dca58, theory);
  auto eca59 = make_shared<Equation>(dca59, theory);
  auto eca60 = make_shared<Equation>(dca60, theory);
  auto eca61 = make_shared<Equation>(dca61, theory);
  auto eca62 = make_shared<Equation>(dca62, theory);
  auto eca63 = make_shared<Equation>(dca63, theory);
  auto eca64 = make_shared<Equation>(dca64, theory);
  auto eca65 = make_shared<Equation>(dca65, theory);
  auto eca66 = make_shared<Equation>(dca66, theory);
  auto eca67 = make_shared<Equation>(dca67, theory);
  auto eca68 = make_shared<Equation>(dca68, theory);
  auto eca69 = make_shared<Equation>(dca69, theory);
  auto eca70 = make_shared<Equation>(dca70, theory);
  auto eca71 = make_shared<Equation>(dca71, theory);
  auto eca72 = make_shared<Equation>(dca72, theory);
  auto eca73 = make_shared<Equation>(dca73, theory);
  auto eca74 = make_shared<Equation>(dca74, theory);
  auto eca75 = make_shared<Equation>(dca75, theory);
  auto eca76 = make_shared<Equation>(dca76, theory);
  auto eca77 = make_shared<Equation>(dca77, theory);
  auto eca78 = make_shared<Equation>(dca78, theory);
  auto eca79 = make_shared<Equation>(dca79, theory);
  auto eca80 = make_shared<Equation>(dca80, theory);
  eca0->merge(eca1);
  eca0->merge(eca2);
  eca0->merge(eca3);
  eca0->merge(eca4);
  eca0->merge(eca5);
  eca0->merge(eca6);
  eca0->merge(eca7);
  eca0->merge(eca8);
  eca0->merge(eca9);
  eca0->merge(eca10);
  eca0->merge(eca11);
  eca0->merge(eca12);
  eca0->merge(eca13);
  eca0->merge(eca14);
  eca0->merge(eca15);
  eca0->merge(eca16);
  eca0->merge(eca17);
  eca0->merge(eca18);
  eca0->merge(eca19);
  eca0->merge(eca20);
  eca0->merge(eca21);
  eca0->merge(eca22);
  eca0->merge(eca23);
  eca0->merge(eca24);
  eca0->merge(eca25);
  eca0->merge(eca26);
  eca0->merge(eca27);
  eca0->merge(eca28);
  eca0->merge(eca29);
  eca0->merge(eca30);
  eca0->merge(eca31);
  eca0->merge(eca32);
  eca0->merge(eca33);
  eca0->merge(eca34);
  eca0->merge(eca35);
  eca0->merge(eca36);
  eca0->merge(eca37);
  eca0->merge(eca38);
  eca0->merge(eca39);
  eca0->merge(eca40);
  eca0->merge(eca41);
  eca0->merge(eca42);
  eca0->merge(eca43);
  eca0->merge(eca44);
  eca0->merge(eca45);
  eca0->merge(eca46);
  eca0->merge(eca47);
  eca0->merge(eca48);
  eca0->merge(eca49);
  eca0->merge(eca50);
  eca0->merge(eca51);
  eca0->merge(eca52);
  eca0->merge(eca53);
  eca0->merge(eca54);
  eca0->merge(eca55);
  eca0->merge(eca56);
  eca0->merge(eca57);
  eca0->merge(eca58);
  eca0->merge(eca59);
  eca0->merge(eca60);
  eca0->merge(eca61);
  eca0->merge(eca62);
  eca0->merge(eca63);
  eca0->merge(eca64);
  eca0->merge(eca65);
  eca0->merge(eca66);
  eca0->merge(eca67);
  eca0->merge(eca68);
  eca0->merge(eca69);
  eca0->merge(eca70);
  eca0->merge(eca71);
  eca0->merge(eca72);
  eca0->merge(eca73);
  eca0->merge(eca74);
  eca0->merge(eca75);
  eca0->merge(eca76);
  eca0->merge(eca77);
  eca0->merge(eca78);
  eca0->merge(eca79);
  eca0->merge(eca80);
  eca0->duplicates();
  eca0->active();
  auto tca = make_shared<Residual>(eca0, "norm");

  list<shared_ptr<Operator>> sa0 = {proje, ex_0, h1};
  list<shared_ptr<Operator>> sa1 = {proje, ex_1, h1};
  list<shared_ptr<Operator>> sa2 = {proje, ex_2, h1};
  list<shared_ptr<Operator>> sa3 = {proje, ex_3, h1};
  list<shared_ptr<Operator>> sa4 = {proje, ex_4, h1};
  list<shared_ptr<Operator>> sa5 = {proje, ex_5, h1};
  list<shared_ptr<Operator>> sa6 = {proje, ex_6, h1};
  list<shared_ptr<Operator>> sa7 = {proje, ex_7, h1};
  list<shared_ptr<Operator>> sa8 = {proje, ex_8, h1};
  list<shared_ptr<Operator>> sb0 = {proje, ex_0, v2};
  list<shared_ptr<Operator>> sb1 = {proje, ex_1, v2};
  list<shared_ptr<Operator>> sb2 = {proje, ex_2, v2};
  list<shared_ptr<Operator>> sb3 = {proje, ex_3, v2};
  list<shared_ptr<Operator>> sb4 = {proje, ex_4, v2};
  list<shared_ptr<Operator>> sb5 = {proje, ex_5, v2};
  list<shared_ptr<Operator>> sb6 = {proje, ex_6, v2};
  list<shared_ptr<Operator>> sb7 = {proje, ex_7, v2};
  list<shared_ptr<Operator>> sb8 = {proje, ex_8, v2};
  auto dsa0 = make_shared<Diagram>(sa0, 1, "");
  auto dsa1 = make_shared<Diagram>(sa1, 1, "");
  auto dsa2 = make_shared<Diagram>(sa2, 1, "");
  auto dsa3 = make_shared<Diagram>(sa3, 1, "");
  auto dsa4 = make_shared<Diagram>(sa4, 1, "");
  auto dsa5 = make_shared<Diagram>(sa5, 1, "");
  auto dsa6 = make_shared<Diagram>(sa6, 1, "");
  auto dsa7 = make_shared<Diagram>(sa7, 1, "");
  auto dsa8 = make_shared<Diagram>(sa8, 1, "");
  auto dsb0 = make_shared<Diagram>(sb0, 0.5, "");
  auto dsb1 = make_shared<Diagram>(sb1, 0.5, "");
  auto dsb2 = make_shared<Diagram>(sb2, 0.5, "");
  auto dsb3 = make_shared<Diagram>(sb3, 0.5, "");
  auto dsb4 = make_shared<Diagram>(sb4, 0.5, "");
  auto dsb5 = make_shared<Diagram>(sb5, 0.5, "");
  auto dsb6 = make_shared<Diagram>(sb6, 0.5, "");
  auto dsb7 = make_shared<Diagram>(sb7, 0.5, "");
  auto dsb8 = make_shared<Diagram>(sb8, 0.5, "");
  auto esa0 = make_shared<Equation>(dsa0, theory);
  auto esa1 = make_shared<Equation>(dsa1, theory);
  auto esa2 = make_shared<Equation>(dsa2, theory);
  auto esa3 = make_shared<Equation>(dsa3, theory);
  auto esa4 = make_shared<Equation>(dsa4, theory);
  auto esa5 = make_shared<Equation>(dsa5, theory);
  auto esa6 = make_shared<Equation>(dsa6, theory);
  auto esa7 = make_shared<Equation>(dsa7, theory);
  auto esa8 = make_shared<Equation>(dsa8, theory);
  auto esb0 = make_shared<Equation>(dsb0, theory);
  auto esb1 = make_shared<Equation>(dsb1, theory);
  auto esb2 = make_shared<Equation>(dsb2, theory);
  auto esb3 = make_shared<Equation>(dsb3, theory);
  auto esb4 = make_shared<Equation>(dsb4, theory);
  auto esb5 = make_shared<Equation>(dsb5, theory);
  auto esb6 = make_shared<Equation>(dsb6, theory);
  auto esb7 = make_shared<Equation>(dsb7, theory);
  auto esb8 = make_shared<Equation>(dsb8, theory);
  esa0->merge(esa1);
  esa0->merge(esa2);
  esa0->merge(esa3);
  esa0->merge(esa4);
  esa0->merge(esa5);
  esa0->merge(esa6);
  esa0->merge(esa7);
  esa0->merge(esa8);
  esa0->merge(esb0);
  esa0->merge(esb1);
  esa0->merge(esb2);
  esa0->merge(esb3);
  esa0->merge(esb4);
  esa0->merge(esb5);
  esa0->merge(esb6);
  esa0->merge(esb7);
  esa0->merge(esb8);
  esa0->duplicates();
  esa0->active();
  auto tsa = make_shared<Residual>(esa0, "source");

  list<shared_ptr<Tree>> trees = {tra, tsa, tec, tca};
  auto fr = make_shared<Forest>(trees);

  fr->filter_gamma();
  list<shared_ptr<Tensor>> gm = fr->gamma();
  const list<shared_ptr<Tensor>> gamma = gm;

  auto tmp = fr->generate_code();

  ofstream fs(fr->name() + ".h");
  ofstream es(fr->name() + "_tasks.h");
  ofstream cs(fr->name() + "_gen.cc");
  ofstream ds(fr->name() + "_tasks.cc");
  ofstream gs(fr->name() + ".cc");
  ofstream gg(fr->name() + "_gamma.cc");
  fs << tmp.ss.str();
  es << tmp.tt.str();
  cs << tmp.cc.str();
  ds << tmp.dd.str();
  gs << tmp.ee.str();
  gg << tmp.gg.str();
  fs.close();
  es.close();
  cs.close();
  ds.close();
  gs.close();
  gg.close();
  cout << std::endl;

  // output
  cout << std::endl << "   ***  Residual  ***" << std::endl << std::endl;
  tra->print();
  cout << std::endl << "   ***  Source  ***" << std::endl << std::endl;
  tsa->print();
  cout << std::endl << "   ***  Energy E2 ***" << std::endl << std::endl;
  tec->print();
  cout << std::endl << "   ***  Correlated norm <1|1> ***" << std::endl << std::endl;
  tca->print();
  cout << std::endl << std::endl;

  return 0;
}

